- .travis.yml
This fixes a bug regarding one of the tests on travis-ci, where the mixed and batched tensorflow test uses too many resources. To fix this, `sudo: required` is added to the relevant matrix entry to ensure this test does not run in a container.
> Merge fixes to travis-ci matrix builds

- strawberryfields/decompositions.py
- strawberryfields/ops.py
- strawberryfields/utils.py
- tests/test_decompositions.py
* do clements decompose lazily
* fixed seed to make decompositions unit test deterministic
* fixed docstring of Interferometer
**Benefits:**
* saves some memory and computational time
* decompositions unit test no longer can fail randomly
none
none
> Slight improvement of Interferometer and related code in decompositions

- strawberryfields/decompositions.py
- strawberryfields/engine.py
- strawberryfields/ops.py
- strawberryfields/parameters.py
- strawberryfields/utils.py
* Minor pep8 fixes.
I noticed some pep8 issues and thought I'd fix them to get started with the codebase.
**Benefits:**
> Petty pep8 changes

- strawberryfields/decompositions.py
- tests/test_decompositions.py
Here's a pull request for triangular decomposition and an associated test. Comments and suggestions welcome!
> Added triangular decomposition

- .travis.yml
- strawberryfields/backends/fockbackend/tests/conftest.py
- strawberryfields/backends/fockbackend/tests/test_displaced_squeezed_state_preparation.py
- strawberryfields/backends/fockbackend/tests/test_fock_probs_gaussian_states.py
- strawberryfields/backends/fockbackend/tests/test_homodyne.py
- strawberryfields/backends/fockbackend/tests/test_squeeze_operation.py
- strawberryfields/backends/fockbackend/tests/test_squeezed_state_preparation.py
- strawberryfields/backends/fockbackend/tests/test_state_preparations.py
- strawberryfields/backends/tfbackend/ops.py
- strawberryfields/backends/tfbackend/states.py
- strawberryfields/backends/tfbackend/tests/conftest.py
- strawberryfields/backends/tfbackend/tests/test_beamsplitter_operation.py
- strawberryfields/backends/tfbackend/tests/test_displaced_squeezed_state_preparation.py
- strawberryfields/backends/tfbackend/tests/test_displacement_operation.py
- strawberryfields/backends/tfbackend/tests/test_fock_gaussian_measurement.py
- strawberryfields/backends/tfbackend/tests/test_fock_measurement.py
- strawberryfields/backends/tfbackend/tests/test_fock_probabilities.py
- strawberryfields/backends/tfbackend/tests/test_fock_probs_gaussian_states.py
- strawberryfields/backends/tfbackend/tests/test_homodyne.py
- strawberryfields/backends/tfbackend/tests/test_loss_channel.py
- strawberryfields/backends/tfbackend/tests/test_modes.py
- strawberryfields/backends/tfbackend/tests/test_nongaussian_gates.py
- strawberryfields/backends/tfbackend/tests/test_rotation_operation.py
- strawberryfields/backends/tfbackend/tests/test_squeeze_operation.py
- strawberryfields/backends/tfbackend/tests/test_squeezed_state_preparation.py
- strawberryfields/backends/tfbackend/tests/test_state_preparations.py
- strawberryfields/backends/tfbackend/tests/test_symbolic.py
Refactor the TF backend tests to use pytest
> Tf backend test refactor

- strawberryfields/utils.py
- tests/frontend/test_utils.py
- tests/integration/test_utils_integration.py
The `utils` module and the associated tests should now work.
Also updated some docs.
> Utils module fixed.

- strawberryfields/backends/tfbackend/ops.py
**Description of the Change:** Tiny update to the `ops.py` file in tf backend
**Benefits:** code is clearer
**Possible Drawbacks:** None that I can see
**Related GitHub Issues:** #75
> Changed index in ops.py

- strawberryfields/ops.py
- tests/backend/test_loss_channel.py
- tests/backend/test_multimode_state_preparations.py
- tests/backend/test_states.py
- tests/backend/test_states_polyquad.py
- tests/backend/test_states_wigner.py
- tests/backend/test_symbolic.py
- tests/conftest.py
- tests/frontend/test_decompositions.py
- tests/frontend/test_ops_decompositions.py
- tests/integration/test_decompositions_integration.py
Try `hbar = 1.7` (say), see which tests fail, fix them.
> Make sure tests run succesfully with a nonstandard hbar value

- doc/code/decompositions.rst
- doc/conventions/decompositions.rst
- doc/conventions/gates.rst
- doc/conventions/states.rst
- doc/index.rst
- doc/references.bib
- doc/references.rst
- doc/xanadu_theme/layout.html
- strawberryfields/decompositions.py
- strawberryfields/program.py
- tests/conftest.py
- tests/frontend/test_decompositions.py
Docstrings updated in the `decompositions` module.
Also fixes a (latent) bug in `graph_embed`.
> Decompositions module docstrings updated.

- strawberryfields/ops.py
- strawberryfields/utils.py
- tests/frontend/test_ops_decompositions.py
- tests/frontend/test_program.py
- tests/frontend/test_utils.py
- tests/integration/test_decompositions_integration.py
This PR
* fixes a number of tests that were skipped or marked as broken
* simplifies hbar handling in the `ops.Gaussian` class
* makes `ops.Gaussian` always a Preparation
* improves some docstrings
* introduces a new general tolerance constant for Decompositions
> Fixing broken or skipped tests

- setup.py
I get a problem similar to this one when setup on win10
https://github.com/rkern/line_profiler/issues/37
> install on win10

- strawberryfields/backends/tfbackend/circuit.py
> reordering possible measurement eval to happen before cond state prep

- doc/code/ops.rst
- doc/code/program.rst
- doc/conf.py
- strawberryfields/devicespecs/device_specs.py
- strawberryfields/engine.py
- strawberryfields/io.py
- strawberryfields/ops.py
- strawberryfields/program.py
- strawberryfields/program_utils.py
- strawberryfields/utils.py
- tests/frontend/test_io.py
- tests/frontend/test_ops_channel.py
- tests/frontend/test_ops_gate.py
- tests/frontend/test_ops_metaoperation.py
- tests/frontend/test_ops_preparation.py
- tests/frontend/test_program.py
- tests/integration/test_decompositions_integration.py
- tests/integration/test_engine_integration.py
- tests/integration/test_measurement_integration.py
- tests/integration/test_ops_integration.py
* Implements the "compilation in stages" model and user interface discussed in issue #108.
* Optimization code moved to `program_utils.py`
* Mocks out `hafnian` when building the docs
* Docstring improvements
> Compilation in stages

- .github/CHANGELOG.md
- strawberryfields/decompositions.py
- strawberryfields/ops.py
- tests/frontend/test_decompositions.py
**Description of the Change:** This PR duplicates the substantive changes of #116 without the troublesome merge conflicts
**Benefits:** can merge into master without any unwanted changes sneaking in
**Possible Drawbacks:** None
**Related GitHub Issues:** #116
> clean version of graph embed changes/fixes without any merge conflicts

- strawberryfields/backends/gaussianbackend/backend.py
- strawberryfields/backends/states.py
- strawberryfields/decompositions.py
- strawberryfields/ops.py
- tests/frontend/test_decompositions.py
- tests/integration/test_measurement_integration.py
Fixes the bug in decompositions/graph_embed and adds a test that catches it (test_embed_graph)
**Benefits:**
One less bug one more tests
~~The test takes about 6 minutes on my pc, because a lot of samples (O(10000)) are needed to catch it~~
> Fixes the bug found by Tom in mean photon per mode

- .github/CHANGELOG.md
- doc/tutorials/tutorial_boson_sampling.rst
Fixes typo in tutorial; closes #132
> fixing typo in boson sampling tutorial

- strawberryfields/api_client.py
The result and circuit fields were being initialized with the wrong variable. This bug fix corrects this issue.
**Benefits:**
> Fix field value reference bug

- doc/index.rst
- doc/tutorials/starship.rst
- strawberryfields/api_client.py
- strawberryfields/engine.py
* Adds missing documentation pages to the table of contents
* Some small sentence changes (i.e., 'xbb file' -> 'Blackbird script')
* Update the Blackbird comments in the example first program for clarity
* Added an (advanced) section to the Starship tutorial, describing program compilation for hardware devices
* Fixed a few Sphinx warnings (section title underline too short, ambiguous `sample` attribute) 
**Benefits:** docs now correctly compile and format, includes an example for users on using `Interferometer` with hardware devices
> Tutorial interferometer

- starship
Fix status code check (200)
**Benefits:**
> Starship hello fix

- setup.py
**Context:**
Some branches (demo and anything branching off of demo) have a cleaned-up version of setup.py. This branch applies this change to master to avoid future merge conflicts.
**Benefits:**
> black setup.py to avoid merge conflicts

- doc/conventions/gates.rst
Corrects typo in definition of CXgate in the documentation
> Corrects typo in definition of CXgate

- .readthedocs.yml
- doc/requirements.txt
Updates `.readthedocs.yml` config file to version 2
> Fix Readthedocs building

- strawberryfields/io.py
- tests/frontend/test_io.py
**Context:**
Adds a helper method to load Blackbird code from string.
**Benefits:**
> Add io.loads function to load from string

- strawberryfields/gbs/vibronic.py
- tests/gbs/test_vibronic.py
> Compute two-mode squeezing parameters

- strawberryfields/gbs/sample.py
- tests/gbs/test_sample.py
> Add vibronic sampler for finite temperature

- .github/CHANGELOG.md
- strawberryfields/_version.py
> Dev version bump

- .github/CHANGELOG.md
- strawberryfields/backends/fockbackend/ops.py
**Context:**
Pylint complains about two unnecessary else statements in the fock backend.
Removed the two unnecessary else statements and added comments
**Benefits:**
Pylint won't complain anymore
None
None
> Remove unnecessary else

- .github/CHANGELOG.md
- Makefile
- strawberryfields/apps/sample.py
- tests/apps/test_sample.py
This adds a `waw_matrix` function that rescales in input adjacency matrix according to the WAW encoding, with the objective of embedding node weights into the adjacency matrix.
> Apps layer: Add WAW adjacency matrix rescaling function

- .github/CHANGELOG.md
- strawberryfields/apps/clique.py
- tests/apps/test_clique.py
This PR adds support for node-weights in the search algorithms of the `clique` module.
> Apps: Update clique functions to accept node weights

- requirements.txt
**Context:**
The test suite runs into problems with getting the link for `thewalrus`.
Updates the link for `thewalrus`.
**Benefits:**
The test suite runs for now.
N/A
N/A
> Update the link for thewalrus in requirements.txt

- .github/CHANGELOG.md
Very minor thing but it's bugging me.
> Correct typo in changelog

- .travis.yml
- doc/introduction/configuration.rst
- doc/introduction/remote.rst
- doc/introduction/tutorials.rst
- setup.py
- strawberryfields/__init__.py
- strawberryfields/api/connection.py
- strawberryfields/api/job.py
- strawberryfields/cli/__init__.py
- strawberryfields/configuration.py
- strawberryfields/engine.py
- tests/api/test_starship_engine.py
- tests/frontend/test_circuitspecs_chip2.py
- tests/frontend/test_sf_cli.py
This is the last change to be merged into the demo branch, before demo is merged into master.
> Rename StarshipEngine to RemoteEngine, starship CLI to sf

- .github/CHANGELOG.md
This PR adds an example to the apps layer part of the changelog
> Add apps example

- strawberryfields/engine.py
Reverts XanaduAI/strawberryfields#341
> Revert "Fixing kwarg assignment bug in engine.py"

- .github/CHANGELOG.md
See https://github.com/XanaduAI/strawberryfields/pull/352/files
> Updates Changelog related to PR 352

- .github/ISSUE_TEMPLATE.md
Correcting a typo in the issue template.
> Correct typos in the template for issues

- tests/integration/test_engine_integration.py
- tests/integration/test_tf_symbolic.py
Should be fixing the last bugs in the tf2 branch 🤞
> Squashing last tf2 bugs

- strawberryfields/circuitspecs/__init__.py
- strawberryfields/circuitspecs/x.py
- strawberryfields/circuitspecs/xstrict.py
- tests/frontend/test_circuitspecs_xstrict.py
Adds a "strict" X compiler. This compiler will not reorder the squeezers.
> Adds "strict" X compiler

- strawberryfields/circuitspecs/__init__.py
- strawberryfields/circuitspecs/xcov.py
- strawberryfields/circuitspecs/xunitary.py
- tests/frontend/test_circuitspecs_xcov.py
- tests/frontend/test_circuitspecs_xunitary.py
Renames compilers, updates dosctrings and lints tests.
> Gaussian compiler X rename

- .github/CHANGELOG.md
updated the changelog after merging #378
> updated changelog

- strawberryfields/circuitspecs/tensorflow.py
- Having the BSgate twice (lines 54 and 58)
> Small modificaiton in tensorflow.py

- strawberryfields/api/job.py
- tests/api/test_connection.py
**Context:**
Adds the `cancel_pending` `JobStatus`.
> Add the cancel_pending JobStatus

- strawberryfields/backends/bosonicbackend/bosoniccircuit.py
Allows generaldyne, homodyne, heterodyne to be performed on distributions with complex weights and means. Also fixes constant errors.
> Gkps mbsqueezing complex

- strawberryfields/tdm/tdmprogram.py
- tests/frontend/test_tdmprogram.py
Updates docstring of `TDMProgram` to make it clear that only Gaussian programs are allowed.
> Update tdm docstring

- strawberryfields/backends/bosonicbackend/bosoniccircuit.py
Updates the fidelity_coherent, fidelity_vacuum functions. Creates parity_val function to check parity of state.
> Gkp paritycheck

- strawberryfields/backends/bosonicbackend/backend.py
- strawberryfields/backends/states.py
> Methods for BaseBosonicState

- .github/CHANGELOG.md
- doc/code/sf_plot.rst
- doc/index.rst
- doc/introduction/photonic_hardware.rst
- strawberryfields/__init__.py
- strawberryfields/_version.py
- strawberryfields/api/connection.py
- strawberryfields/engine.py
- strawberryfields/io.py
- strawberryfields/ops.py
- strawberryfields/plot.py
- strawberryfields/program.py
- strawberryfields/tdm/tdmprogram.py
- tests/api/test_connection.py
- tests/frontend/test_engine.py
- tests/frontend/test_io.py
- tests/frontend/test_ops_gate.py
- tests/frontend/test_sf_plot.py
- tests/frontend/test_tdmprogram.py
Merges `master` into `gkps`, so that `gkps` is not behind `master`.
> Gkps merge master

- strawberryfields/backends/bosonicbackend/backend.py
- strawberryfields/backends/bosonicbackend/bosoniccircuit.py
- Bosonic backend now supports Thermal, Vac, Coherent, Squeezed, DispSqueezed, Gaussian state prep
- Minor debugging in homodyne/heterodyne, thermal_loss, mbsqueezing
**Context:** Adds gaussian state preparations to bosonic backend
**Description of the Change:** 
- Bosonic backend now supports Thermal, Vac, Coherent, Squeezed, DispSqueezed, Gaussian state prep
- Minor debugging in homodyne/heterodyne, thermal_loss, mbsqueezing
- Comments out functions that are not currently implemented
**Benefits:**
> Gaussian state preparation + debugging

- strawberryfields/backends/bosonicbackend/backend.py
- strawberryfields/backends/bosonicbackend/ops.py
- strawberryfields/backends/states.py
- tests/backend/test_heterodyne.py
- tests/backend/test_loss_channel.py
- tests/backend/test_mbsqueeze_operation.py
- tests/backend/test_multimode_state_preparations.py
- tests/backend/test_postselection.py
- tests/backend/test_states.py
- tests/backend/test_states_probabilities.py
- tests/bosonic_files/test_backend-ops.py
- tests/conftest.py
Please complete the following checklist when submitting a PR:
If you've fixed a bug or added code that should be tested, add a test to the
test directory!
If you do make documentation changes, make sure that the docs build and
render correctly by running `make docs`.
change, and including a link back to the PR.
[PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
We check all of our code against [Pylint](https://www.pylint.org/).
To lint modified files, simply `pip install pylint`, and then
run `pylint strawberryfields/path/to/file.py`.
When all the above are checked, delete everything above the dashed
line and fill in the pull request template.
------------------------------------------------------------------------------------------------------------
**Context:** Creating tests …
> Gkps tests

- strawberryfields/backends/gaussianbackend/ops.py
- tests/frontend/test_tdmprogram.py
Previously the indices used internally in a number of functions in `ops.py` where generated as sets without necessarily being ordered. This PR turns those sets into lists and sorts them.
> Fix gaussian ops

- .github/workflows/tests.yaml
- strawberryfields/backends/bosonicbackend/bosoniccircuit.py
- tests/bosonic_files/test_backend_bosoniccircuit.py
- tests/bosonic_files/test_backend_ops.py
**Context:** Adds core functions for the bosonic backend, and relevant tests
**Description of the Change:** The bosoniccircuit.py file contains the relevant functions for manipulating modes in the bosonic backend as a circuit is performed.
**Benefits:**
> Adds bosoniccircuit.py and its tests

- .github/CHANGELOG.md
- strawberryfields/_version.py
Celebrating yet another Strawberry Fields release by bumping the version to 0.19.0-dev. 🥳 🍓
> Increment version to 0.19.0-dev

- .github/CHANGELOG.md
- strawberryfields/compilers/__init__.py
- strawberryfields/compilers/gaussian_merge.py
- tests/frontend/compilers/test_gaussianmerge.py
- tests/frontend/compilers/test_gaussianunitary.py
Adds hybrid Gaussian Merge compiler that merges gaussian operations into Gaussian Tranform operations in a program with non-Gaussian and Gaussian operations. 
Please complete the following checklist when submitting a PR:
If you've fixed a bug or added code that should be tested, add a test to the
test directory!
If you do make documentation changes, make sure that the docs build and
render correctly by running `make docs`.
strawberryfields`. You will need to have the Black code format installed: `pip install
black`.
change, and including a link back to the PR.
[PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
We check all of our code against [Pylint](https://www.pylint.org/).
To lint modified files, simply `pip install pylint`, and then
run `pylint …
> [unitaryHACK] Strawberry Fields: Gaussian Merge

- strawberryfields/backends/bosonicbackend/backend.py
- tests/backend/test_bosonic_backend.py
Adds new tests for threshold detection. So far they seem to fail.
> Adds extra tests

- .github/CHANGELOG.md
- strawberryfields/_version.py
Increment version to 0.20.0-dev after latest release. 🍓
> Increment version to 0.20.0-dev

- .github/workflows/docs.yml
- doc/requirements.txt
- requirements-ci.txt
- requirements.txt
- strawberryfields/backends/tfbackend/ops.py
**Context:**
Merging master into `integrate-xanadu-cloud-client` branch.
**Benefits:**
> Merge master into branch

- .github/CHANGELOG.md
- doc/requirements.txt
- requirements-ci.txt
- requirements.txt
- setup.py
- strawberryfields/_version.py
Increment version to 0.20.0 to prepare for release. 🎉
> Increment version to 0.20.0

- .github/CHANGELOG.md
- strawberryfields/_version.py
Incrementing version number to 0.21.0-dev post release.
> Increment version to 0.21.0-dev

- .github/CHANGELOG.md
- requirements.txt
- setup.py
- strawberryfields/_version.py
**Context:**
Getting ready for a new release!
Bumps version number to 0.21.0
> Increment version number to 0.21.0

- .github/CHANGELOG.md
- strawberryfields/_version.py
**Context:**
Strawberry Fields has been released!
Bump version number to 0.22.0-dev
> Increment version number to 0.22.0-dev

- .github/CHANGELOG.md
- strawberryfields/_version.py
Strawberry Fields v0.22.0 has been released! 🍓
> Incrementing the version number to 0.23.0-dev

- .github/CHANGELOG.md
- strawberryfields/_version.py
Incrementing version to 0.23.0-dev.
> Increment version to 0.23.0-dev.

- .github/CHANGELOG.md
- strawberryfields/_version.py
> Increment back to 0.24.0-dev
