strawberryfields/backends/gaussianbackend/ops.py
Some minor improvements to `fock_prob()` that should make the code a bit more readable and which, in test runs with cProfile, reduce the average run-time of the unite tests of the `gaussian` backend by a few percent (for larger systems the difference should be more substantial). Hope you find these useful!
=> Minor improvements in `fock_prob()`

strawberryfields/backends/tfbackend/circuit.py, strawberryfields/backends/tfbackend/ops.py
Adds caching of numerical prefactors to the beamsplitter gate in the tensorflow backend
**Benefits:**
Saves space on the computational graph
None that I can see. These prefactors are created once in the computational graph and re-used as needed, rather than being re-created for every beamsplitter
NA
=> Caching of numerical prefactors as tensors for beamsplitter

strawberryfields/backends/base.py, strawberryfields/backends/fockbackend/backend.py, strawberryfields/backends/fockbackend/circuit.py, strawberryfields/backends/gaussianbackend/backend.py, strawberryfields/backends/gaussianbackend/gaussiancircuit.py, strawberryfields/backends/states.py, strawberryfields/backends/tfbackend/backend.py, strawberryfields/backends/tfbackend/circuit.py
* Adds a reset method to modeMap, so that the modeMap can be reset to the initial state it was instantiated in.
* Add a reset method to the `GaussianCircuit` class - now the reset is done manually, rather than applying loss to all modes.
* Updated the reset methods of the Fock and Tensorflow backends so that the modeMap is also reset
* Updated `all_fock_probs` in the case of a pure state, to properly reshape the returned array.
**Benefits:**
* When resetting a backend, the backend circuit now returns to the original number of modes initialised by the engine.
* `all_fock_probs` returns an array of the same shape regardless whether the state was pure or mixed.
**Related GitHub Issues:** #10 and #11
=> Fixes for bug #10 and bug #11

doc/conf.py, doc/conventions/gates.rst, strawberryfields/backends/base.py, strawberryfields/backends/fockbackend/__init__.py, strawberryfields/backends/fockbackend/backend.py, strawberryfields/backends/fockbackend/circuit.py, strawberryfields/backends/fockbackend/ops.py, strawberryfields/backends/tfbackend/__init__.py, strawberryfields/backends/tfbackend/backend.py, strawberryfields/backends/tfbackend/circuit.py, strawberryfields/backends/tfbackend/ops.py, strawberryfields/ops.py, tests/test_nongaussian_gates.py, tests/test_toolchain.py
This pull request adds the cross-Kerr interaction to Strawberry Fields. This is supported by both the Fock and Tensorflow backends, in numerical and symbolic mode, mixed and batched operation. A cross-Kerr test has been added to the file `test_non_gaussian_gates.py`, and a frontend quantum operation `CKgate` has been added.
In addition, a few small bugfixes were made to the documentation. In particular, Sphinx would not build ops.py and parameters.py as np.pi was not mocked out correctly.
**Benefits:**
Can now natively perform the cross-Kerr interaction in Strawberry Fields.
None that I can think of.
n/a
=> Added the cross-Kerr interaction

doc/conventions/decompositions.rst, strawberryfields/backends/base.py, strawberryfields/backends/gaussianbackend/backend.py, strawberryfields/backends/gaussianbackend/gaussiancircuit.py, strawberryfields/ops.py, tests/test_decompositions.py, tests/test_multimode_state_preparations.py
This pull request makes the following changes:
* Adds the `prepare_gaussian_state` BaseGaussian API method, and implements it in the Gaussian backend
* Adds a test for `prepare_gaussian_state`
* Changes the frontend operation `CovarianceState` to `Gaussian`, and provides the ability for `Gaussian` to also explicity prepare the Gaussian state, rather than perform the Williamson decomposition.
**Benefits:**
This puts the Gaussian backend on equal footing with the Fock backends, now all backends support multimode arbitrary state preparation.
=> Gaussian multimode

strawberryfields/backends/fockbackend/__init__.py, strawberryfields/backends/fockbackend/backend.py, strawberryfields/backends/fockbackend/circuit.py, strawberryfields/backends/tfbackend/__init__.py, strawberryfields/backends/tfbackend/backend.py, strawberryfields/backends/tfbackend/circuit.py, strawberryfields/backends/tfbackend/ops.py
As per the title, this pull request renames the `QReg` class to `Circuit`. 
**Benefits:**
The name now more closely corresponds to the file name `circuit.py`, and matches the Gaussian class `GaussianCircuit`.
None as far as I can see.
n/a
=> Renamed QReg in the Fock backends to Circuit

doc/conventions/others.rst, strawberryfields/backends/base.py, strawberryfields/backends/gaussianbackend/backend.py, strawberryfields/backends/gaussianbackend/gaussiancircuit.py, strawberryfields/ops.py, tests/test_gate.py, tests/test_loss_channel.py, tests/test_toolchain.py
* Thermal loss channel is now implemented in the Gaussian backend
* Added `thermal_loss()` to `BaseBackend`. At the moment, since it is not implemented in the Fock backends, attempting to use it there will raise a `NotImplementedError`.
* Added `ThermalLossChannel` operation to `ops.py`, and moved the common channel merge method up to `Channel`.
* Added backend tests for `thermal_loss` to the `test_loss_channel.py` file.
* Added documentation for the thermal loss channel to `doc/conventions/others.rst`.
**Benefits:**
* The addition of another loss channel.
* Currently not implemented in the Fock backends - a Kraus operator mapping will need to be implemented.
* n/a
=> New channels

examples/custom_operator.py, strawberryfields/utils.py, tests/test_operator.py
I still need to add a couple of unit tests, etc. and but I thought it made sense to submit an early PR to check if the approach meets your expectations.
You can check `examples/custom_operator.py` to see how the new feature is supposed to be used.
=> Allow turning circuits into operators

strawberryfields/decompositions.py, tests/test_decompositions.py
Replaced the permutation matrix originally applied on output to permute it into canonical symplectic form with a rotation matrix that is constructed using SVD. The earlier approach did not return matrices in the canonical symplectic form if one or more of the Bloch-Messiah singular values were degenerate; this is fixed now.
**Benefits:**
Bloch-Messiah now works for input matrices with degenerate singular values.
Fixes #14, which was an instance of degenerate singular values (both equal to the φ = 1.61803)
=> Fixed Bloch-Messiah bug arising when singular values were degenerate

strawberryfields/decompositions.py, tests/test_decompositions.py
Creating this pull request to get the conversation going about better support for linear optics decompositions. 
The first commits add support for the final form of the Clements et al. decomposition, i.e. having the phases at the end (as in Equation 5) rather than in the middle (as in Equation 4, which is the current implementation). This Equation 5 decomposition is more symmetric than the intermediate one, which could make it more robust. This form also makes it easier to implement a tensor-network simulation of linear optics. 
This new code is for now only in an additional function, but could replace the current function. As this is quite central to some of the sf functionality, it's better to be careful. Would love to learn more about what you folks think is the best way to go about …
=> Better decompositions: Clements et al. (and possibly Reck?)

.github/CHANGELOG.md, strawberryfields/_version.py, strawberryfields/utils.py, tests/defaults.py, tests/test_utils.py
------------------------------------------------------------------------------------------------------------
Added two new utilities to extract a numerical representation of a circuit from an Engine object: `extract_unitary` and `extract_channel`.
The first returns a numerical array that represents a unitary transformation (and it's applicable to the case where in the circuit specification there are only ops of type `Gate`).
The second returns a numerical array that represents a channel (and it's applicable to the case where in the circuit specification there are only ops of type `Gate` or `Channel`).
Both functions support an option to vectorise the indices that correspond to different modes. This makes `extract_unitary` return a matrix, and …
=> Extract methods

.gitignore, .travis.yml, strawberryfields/backends/fockbackend/backend.py, strawberryfields/backends/fockbackend/ops.py, strawberryfields/backends/fockbackend/tests/conftest.py, strawberryfields/backends/fockbackend/tests/test_displacement.py, strawberryfields/backends/fockbackend/tests/test_squeeze.py
Changes:
* Slightly modifies the imports of the Fock backend, so that they import anything from the main Strawberry Fields package is imported via an absolute path. This allows the Fock backend to be imported independently of Strawberry Fields.
* Added a `test` folder to the `fockbackend` submodule
* Added a pytest `conftest.py` configuration file, which defines the main test environment variables (cutoff, hbar, batched, pure, etc.) as pytest fixtures. Also creates a fixture for initializing the backend with a specific number of subsystems.
* Ported over `test_displacement_operator.py` and `test_squeezing.py`. *Note that I changed the names of the new tests to match the Fock backend methods they are testing.*
* Linted the two ported tests using pylint, and added the license boilerplate.
* …
=> Added pytest boilerplate to the fock backend (50)

README.rst, doc/installing.rst
**Description of the Change:** makes clear in the readme and documentation that Strawberry Fields cannot support Python 3.7 due to TensorFlow not supporting this Python version.
**Benefits:** clarity to users on Python 3.7
**Related GitHub Issues:** #35
=> update readme and docs to explain python 3.7 support

pytest/backend/test_beamsplitter_operation.py, pytest/backend/test_displaced_squeezed_state_preparation.py, pytest/backend/test_displacement_operation.py, pytest/backend/test_fock_measurement.py, pytest/backend/test_homodyne.py, pytest/backend/test_modes.py, pytest/backend/test_multimode_state_preparations.py, pytest/backend/test_nongaussian_gates.py, pytest/backend/test_rotation_operation.py, pytest/backend/test_squeeze_operation.py, pytest/backend/test_squeezed_state_preparation.py, pytest/backend/test_state_preparations.py, pytest/backend/test_symbolic.py, pytest/integration/test_ops_integration.py
* Added the already ported Fock backend tests from #55 to the top level pytest folder
* Ported over the `test_multimode_state_preparation` test, splitting it into a backend test, and an integration test (added to `test_ops_integration.py`).
Once this is merged, the following will have to take place in a new PR:
1. Remove the old unittest `tests` folder, and rename the `pytest` folder to `tests`
2. Update the top level makefile and the TravisCI config
3. Update the section in the documentation on running the tests.
=> Pytest backend

strawberryfields/ops.py, strawberryfields/program.py
Remove the unused `Command.decomp` instance attribute, which at some point used to indicate that the Command is the result of a decomposition. It's never read, only written.
If such metadata is needed at some later date, it's easiest to implement at the top-level `Operation.decompose` method.
=> Remove Command.decomp

tests/conftest.py, tests/frontend/test_circuitdrawer.py, tests/frontend/test_ops_decompositions.py, tests/integration/test_engine_integration.py
To mark tests that will currently fail due to the underlying code-base being broken, I've created the new pytest mark `pytest.mark.broken`, as opposed to manually skipping the test. This allows us to easily find and fix the broken tests in the future as the code base regains stability.
Use this at the top of a test module:
```python
pytestmark = pytest.mark.broken
```
or as a decorator on a test function/test class:
```python
@pytest.mark.broken
```
along with a comment as to _why_ the test is currently broken.
=> Created a pytest mark for broken tests

strawberryfields/__init__.py, strawberryfields/backends/base.py, strawberryfields/backends/fockbackend/backend.py, strawberryfields/backends/fockbackend/circuit.py, strawberryfields/backends/gaussianbackend/backend.py, strawberryfields/backends/gaussianbackend/gaussiancircuit.py, strawberryfields/backends/gaussianbackend/states.py, strawberryfields/backends/states.py, strawberryfields/backends/tfbackend/backend.py, strawberryfields/backends/tfbackend/circuit.py, strawberryfields/backends/tfbackend/states.py, strawberryfields/engine.py, strawberryfields/ops.py, tests/conftest.py, tests/frontend/test_ops_gate.py, tests/integration/test_algorithms.py, tests/integration/test_decompositions_integration.py, tests/integration/test_ops_integration.py
This PR simplifies the way hbar is handled. Previously many different objects kept track of the hbar value associated with the object data. This enabled practices that are not useful and that could be outright harmful, like combining gates with different hbar values in the same circuit, and made the call interfaces cluttered.
Changes:
* The backend API is now entirely hbar-independent, i.e. every backend API method is defined in terms of `a` and `a^\dagger` only, not x and p.
* The backends always explicitly use hbar=2 internally.
* hbar is now a global, frontend-only variable that the user can set at the beginning of the session. It is used at the `Operation.apply()` level to scale the inputs and outputs of the backend API calls as needed, and inside the …
=> Eliminate hbar from backend API.

doc/code/engine.rst, doc/code/example_use.rst, doc/op_conventions.rst, strawberryfields/__init__.py, strawberryfields/engine.py, strawberryfields/ops.py, strawberryfields/parameters.py, strawberryfields/program.py, strawberryfields/utils.py, tests/conftest.py, tests/frontend/test_engine.py, tests/frontend/test_program.py, tests/integration/test_algorithms.py, tests/integration/test_decompositions_integration.py, tests/integration/test_engine_integration.py, tests/integration/test_hbar_integration.py, tests/integration/test_ops_integration.py, tests/integration/test_tf_symbolic.py, tests/integration/test_utils_integration.py
Introduces the BaseEngine ABC and the LocalEngine child class. Engine is kept as an alias for LocalEngine.
The Engine API has been changed slightly:
* `LocalEngine.run()` returns a `Result` object that contains both a state object and measurement samples.
* The complicated and error-prone way kwargs were used has been simplified by introducing the new kwargs-like arguments `backend_options` and `state_options`.  `LocalEngine.run()` passes the actual kwargs only to `Operation.apply()`
**Benefits:**
Now we can start working on the remote engines.
=> LocalEngine class

doc/index.rst, doc/references.bib, strawberryfields/__init__.py, tests/frontend/test_about.py
Implements issue #70.
Adds two top-level functions:
* `about()`, which prints human-readable system info including installed versions of various Python packages
* `cite()`, which prints a bibtex citation for SF
I also added the SF citation to the `references.bib` file.
**Benefits:**
Complete, informative bug reports are easier for the users to produce.  Possibly more citations :)
=> Add about() and cite() functions

README.rst, doc/conf.py, doc/installing.rst, examples/gaussian_boson_sampling.py, requirements.txt, setup.py, strawberryfields/backends/__init__.py, strawberryfields/backends/tfbackend/__init__.py, strawberryfields/parameters.py, strawberryfields/utils.py, tests/backend/test_tf_import.py, tests/conftest.py, tests/frontend/test_parameters.py, tests/integration/test_engine_integration.py, tests/integration/test_parameters_integration.py, tests/integration/test_tf_symbolic.py, tests/integration/test_utils_integration.py
* Removes TF from `setup.py` (it is install in requirements.txt for our continuous integration).
* Adds a try-except for tensorflow import in `parameters.py`. If there is an `ImportError`, the module `tf` is simply mocked out.
* Added TensorFlow import logic and a useful exception message to the `TFBackend`, that checks whether TensorFlow is installed and is the correct version. If not, information is given to the user on how to install SF with TensorFlow support.
**Benefits:**
* Strawberry Fields will now install and run correctly without TensorFlow dependence. The exception message above will only be triggered if the user specifically requests the `'tf'` backend.
* This is a stopgap solution; at some point, we should aim to spin the …
=> Remove TF dependency from Strawberry Fields

strawberryfields/devicespecs/base.py, strawberryfields/devicespecs/fock.py, strawberryfields/devicespecs/gaussian.py, strawberryfields/devicespecs/tensorflow.py, strawberryfields/ops.py, strawberryfields/program.py, tests/frontend/test_ops_metaoperation.py
Replaces the `ops.New` singleton object with a similarly named function that creates a `New_modes` instance and appends it to the `Program`.
**Benefits:**
Previously, since there was just a single object, the `New_modes.n` instance variable would be overwritten each time `New.__call__` was called. `New_modes.n` is currently only used by `New_modes.__str__`, which is why this bug escaped notice.
This should be a drop-in replacement.
=> New_modes bugfix.

strawberryfields/ops.py, tests/frontend/test_ops_metaoperation.py
Now `ops.New()` raises an exception if it is called outside a Program context, instead of just failing with a cryptic error message.
Also improved some related tests.
=> Adds a Program context check to ops.New(). Updates related tests.

doc/conventions/decompositions.rst
The macros \x and \p already put hats, no need to add them by hand. Now it should render with only a single hat on top of the canonical operators instead of two.
=> Removing double hats

default_config.toml, requirements.txt, setup.py, strawberryfields/configuration.py, tests/frontend/test_about.py, tests/frontend/test_configuration.py
**Description of the Change:** Adds a basic configuration module to SF.
**Benefits:**
* Stores default configuration
* Platform-independent search of configuration file locations
* Environment variables have the same name, prefixed with `SF_{SECTION}_`. If they exist, they take precedence over a configuration file.
=> Configuration file for Strawberry Fields

setup.py
Fixed requirements typo that made setup.py skip installing toml
**Benefits:**
Installing from source will include all requirements now
=> Update setup.py requirements

.travis.yml
Remove __sudo:__ tag in .travis.yml because it is deprecated.
**Benefits:**
Simplify, remove dead code.
I can not think of any drawbacks.
=> Travis CI: The sudo tag is now deprecated in Travis

doc/glossary.rst, doc/index.rst
Added a basic glossary page to the docs.
I wasn't able to provide a great definition for some of the terms, which IMO highlights the need for a glossary :)
**Benefits:**
Makes it easier to keep the terminology clear.
=> Add a basic glossary to the docs

.github/CHANGELOG.md, strawberryfields/__init__.py, strawberryfields/_version.py, strawberryfields/backends/tfbackend/__init__.py, strawberryfields/circuitspecs/chip0.py, strawberryfields/parameters.py, strawberryfields/utils.py
* Replaces all instances of `ModuleNotFoundError` with `ImportError`.
* Updates the `Chip0` template to use `MeasureFock() | [0, 1, 2, 3]`, which will allow correct fock measurement behaviour when simulated on the Gaussian backend. Also updates the gate topology of beamsplitters and phase shifters.
* Incremented the version number to 0.11.1, allowing for a small bugfix release once merged.
* Updated the changelog, brought the v0.11.0 entry up to date with the GitHub release notes.
**Benefits:**
* `ModuleNotFoundError` is a subclass of `ImportError`, that was introduced with Python 3.6+. So this should have no functionality change. However, this will now allow SF to be importable on Python 3.5; required since TF==1.3 is only supported on Python 3.5 on …
=> Remove `ModuleNotFoundError` from the codebase and update chip0 spec

.github/CHANGELOG.md, strawberryfields/engine.py, tests/integration/test_engine_integration.py
* Removed the `LocalEngine.run()` argument `return_state`. Now a state object is returned iff modes is not an empty sequence.
**Benefits:**
One less argument. I don't see any uses for state objects with no modes.
=> Engine.run: return_state removed.

strawberryfields/engine.py, tests/frontend/test_engine.py
**Context:** Currently, ``name`` is set as a required positional argument of `StarshipEngine.run()`. However, this is not needed, as all loaded blackbird programs, as well as all SF programs, already have names.
* Removes the `name` positional argument from `StarshipEngine`
* Leaves a TODO comment, as a reminder to modify `StarshipEngine` to support shots pass-through once #130 is merged into master.
**Benefits:** name no longer needs to be passed to `eng.run()`, this is extracted automatically from the `Program.name` attribute.
=> remove name

strawberryfields/decompositions.py
Removes wrong description of what and adjacency matrix in the description of graph embed
**Benefits:**
=> Removes wrong description of adjacency matrices

strawberryfields/circuitspecs/gbs.py, tests/frontend/test_program.py
**Context:** During GBS compilation, the call to `networkx.lexicographical_topological_sort()` permutes the returned order of the measured registers, since all permutations are equivalent.
**Description of the Change:** After the topological sort, the measured registers are sorted in ascending order in the compiled program. A test to confirm this behaviour is also added.
**Benefits:** This avoids unexpected results, as programs containing `MeasureFock() | q` previously could compile to `MeasureFock() | (q[0], q[2], q[1], q[3])`.
**Possible Drawbacks:** It would be nicer to preserve the order the user specifies the modes in. This is probably not possible, however, due to the topological sort. Further, the user should probably expect differences like this to occur when compiling.
**Related …
=> Add a `sorted()` call to `GBSSpec.compile()`

strawberryfields/io.py, strawberryfields/program.py, tests/frontend/test_io.py
* Makes `Program.target` a property, to make it less likely that a user manually changes the value
* Fixes a bug where compilation and engine run options (such as shots) were not being saved to Blackbird scripts. Adds a test to check this works as intended.
**Benefits:**
* Now slightly harder to 'fake' compilation
* Shots will be correctly saved to a blackbird program
* Still possible to fool compilation, by instead changing the hidden attribute. The question is, is this sufficient? Or should we also change the engine logic to force re-compilation every time? My preference is to keep the existing engine logic, just to avoid the overhead of the non-efficient compilation process.
=> Change `Program.target` to a property, and ensure run options are saved to Blackbird scripts

strawberryfields/api_client.py, strawberryfields/engine.py, tests/frontend/test_api_client.py, tests/frontend/test_engine.py
When a job fails to execute and the server returns a correct error message regarding the job execution failure, forward this information to the user.
**Benefits:**
=> Show job failed error

tests/backend/test_nongaussian_gates.py
Added test for cubic phase gate in 'tests/backend/test_nongaussian_gates.py'
**Benefits:**
Allows fock and tf backend testing of the cubic phase gate.
=> Added test for cubic phase gate

.github/CHANGELOG.md, doc/conf.py, doc/gallery/scattershot-boson-sampling/scattershot-bs.ipynb, doc/installing.rst, doc/tutorials/tutorial_boson_sampling.rst, doc/tutorials/tutorial_gaussian_boson_sampling.rst, requirements.txt, setup.py, strawberryfields/__init__.py, strawberryfields/backends/base.py, strawberryfields/backends/gaussianbackend/backend.py, strawberryfields/backends/gaussianbackend/ops.py, strawberryfields/backends/tfbackend/__init__.py, strawberryfields/circuitspecs/gaussian.py, strawberryfields/circuitspecs/gbs.py, strawberryfields/decompositions.py, strawberryfields/ops.py, tests/backend/test_tf_import.py, tests/backend/test_threshold_measurement.py, tests/frontend/test_about.py, tests/frontend/test_ops_decompositions.py
Adds threshold (torontonian) sampling to the capabilities of the Gaussian backend.
**Benefits:**
Threshold samples can be generated directly instead of doing PNR and then threshold by hand. Should give significant saving in time and it is useful for apps upstream.
=> Adds Torontonian sampling support to the Gaussian backend

strawberryfields/ops.py
During the creation of `BipartiteGraphEmbed` (#150), the name of a variable was changed from `mean_photon_per_mode` to `mean_photon`, which was previously determined to be too unclear. This PR resets all mentions of `mean_photon` in `GraphEmbed` and `BipartiteGraphEmbed` to be `mean_photon_per_mode`
=> fixes erroneous name introduced during #150

doc/conventions/gates.rst
Correct incorrect order in decomposition of CXgate in the conventions page. Note that the implementation in ops is correct.
=> Incorrect order in decomposition of CXgate

.github/CHANGELOG.md, setup.py, strawberryfields/backends/gaussianbackend/backend.py, strawberryfields/backends/gaussianbackend/gaussiancircuit.py, tests/backend/test_fock_measurement.py, tests/integration/test_measurement_integration.py
Removes the restriction of zero mean for PNR sampling. This is allowed by recently added capabilities in the hafnian library.
**Benefits:**
Can do more sophisticated sampling. Also useful in Franck-Condon factor sampling.
=> Removes the restriction of zero mean for PNR sampling

doc/conf.py, strawberryfields/apps/graph/resize.py, strawberryfields/apps/graph/utils.py
Adding examples of function use in small code snippets can really help the reader get a quick understanding of the function. We would like to do this for functions in the applications layer, and this PR provides code snippets for max-clique based functions in `graph.utils` and also the `graph.resize.clique_swap` function.
=> Add example code to docstrings for utils

strawberryfields/apps/graph/resize.py
Adding examples of function use in small code snippets can really help the reader get a quick understanding of the function. We would like to do this for functions in the applications layer, and this PR provides code snippets for max-clique based functions in `graph.resize`.
=> Add example code to docstrings for resize

doc/references.bib, strawberryfields/apps/graph/max_clique.py, tests/apps/test_graph_max_clique.py
We are providing the local search algorithm with periods of clique growth and clique swapping. This function takes in cliques one at a time, so the user can interface by:
1. generating subgraphs from GBS
2. shrinking them to cliques
3. feeding them through the local search function.
Time permitting, we may consider a subsequent PR which combines all these into a single function.
=> Provide local search algorithm for maximum clique

doc/code/apps/graph.max_clique.rst, doc/index.rst, strawberryfields/apps/graph/max_clique.py, strawberryfields/apps/graph/resize.py, strawberryfields/apps/graph/utils.py, strawberryfields/apps/sample.py
The purpose of this PR is to make the applications layer accessible in the SF documentation by adding in as a table of contents. This does not include a full integration (e.g., giving more details about the apps layer in the top level `index.rst` file), which can be done at a later date once the applications layer matures.
This PR also includes a check through of the documentation for the recently added maximum clique functionality.
=> Provide applications layer in docs and polish max clique documentation

.github/CHANGELOG.md, strawberryfields/decompositions.py, tests/frontend/test_decompositions.py
**Context:**
The sign of the phases returned by `strawberryfields.decompositions.rectangular_symmetric` depended on algorithm details due to the incorrect use of `numpy.fmod` instead of the standard python modulo (`%`) operator. 
Fixes bug in `strawberryfields.decompositions.rectangular_symmetric` so its returned phases are all in the interval [0, 2*pi[, adds tests for this, and corrects a bug in the function docstring. 
**Benefits:**
The user can be sure that the returned phases are in the interval from 0 to 2 pi. 
-
#192 and part of #193
=> Fix issue #192 and part of #193 (decompositions.rectangular_*)

examples_gbs/run_tutorial_sample.py, strawberryfields/gbs/data.py, strawberryfields/gbs/sample.py, strawberryfields/gbs/similarity.py, tests/gbs/test_sample.py, tests/gbs/test_similarity.py
Since realistic GBS devices will have losses, it makes sense to provide this in the applications layer. Since loss is already part of SF, we only need to change the program fed to the SF Engine, as well as updating tests and docs.
=> GBS: Add ability to simulate losses in GBS

strawberryfields/gbs/sample.py, tests/gbs/test_sample.py
Currently, the `gbs.sample.sample()` function raises:
`AttributeError: 'list' object has no attribute 'tolist'`
when called with `n_samples = 1` (which, ironically, is actually the default).
This is because `eng.run`, which is called within `sample()`, returns:
- A list if `n_samples = 1`
- A numpy array if `n_samples > 1`
To fix this, we have changed the `sample()` function to internally check when `n_samples = 1` and when that is the case: for a sample `s`, return `[s]`. E.g., if the sample is `[0, 1, 3, 0]` the return is `[[0, 1, 3, 0]]`. Although this seems like an unnecessary embedding, it means that the output form of `sample()` doesn't change with `n_samples`, i.e., always `len(sample()) = n_samples` and the return is a list of samples.
Alternatively, we could change `sample()` to …
=> GBS Bug: Fix single shot sampling

doc/xanadu_theme/static/xanadu.css_t
Readthedocs is currently placing adverts: https://docs.readthedocs.io/en/stable/advertising/ethical-advertising.html
This results in a small banner at the bottom of the documentation.
One problem is that it covers the last entry in our table of contents sidebar - currently the apps layer tutorials. This PR ensures that the banner ad no longer covers this entry.
It also fixes a minor bug in the behaviour of the search box when scrolling in the sidebar.
=> Fix sidebar when adverts are showing

strawberryfields/gbs/sample.py
When running the `sample.sample()` function in the applications layer, the user is presented with the following warning:
While it might make sense to present the user with this error if they have designed an SF Program, it doesn't when calling `sample()` which creates the program/engine on their behalf.
This PR suppresses the warning in the `sample()` function.
=> GBS: Fix sample warning

examples_gbs/run_tutorial_dense.py, examples_gbs/run_tutorial_max_clique.py, examples_gbs/run_tutorial_points.py, examples_gbs/run_tutorial_sample.py, examples_gbs/run_tutorial_similarity.py
The documentation currently has a workaround to use dynamic plotly plots:
First, the plot is saved:
```python
plot_graph = plot.graph(g)
plotly.offline.plot(plot_graph, filename="graph.html")
```
Then, the plot is loaded in `rst`:
```rst
```
However, when executing the script directly the user could simply call the following:
```python
plot.graph(g).show()
```
We have already added a note to `similarity` and `subgraph` tutorials to explain this. This PR adds the note to the remaining tutorials.
=> GBS Docs: Add plotting note to tutorial

doc/conf.py
A [recent update](https://github.com/sphinx-gallery/sphinx-gallery/releases/tag/v0.5.0) to sphinx-gallery has caused an unwanted output box to appear when plotting:
This output is shown because sphinx-gallery now looks for a html and string representation on the last line of each codeblock. The string representation of `plotly.offline.plot(plot_1, filename="Points.html")` is just `'Points.html'` and this is hence what is shown in the output box.
This PR removes the unwanted output box by preventing sphinx-gallery from searching for the string representation. This is done just by telling sphinx-gallery to behave as it did before the update, as described here: https://sphinx-gallery.github.io/stable/configuration.html#capture-repr. The result is:
=> Remove output string from plots

strawberryfields/apps/plot.py
Currently, users could only access square-layout plots. This remains the default, but users are now able to specify a rectangular layout.
=> Apps plotting: allow user to specify both x and y dimension of plots

examples_apps/run_tutorial_points.py, strawberryfields/apps/points.py, tests/apps/test_points.py
Based on user feedback, we have decided to rename the `kernel` function in the `points` module to `rbf_kernel`. This helps specify the type of kernel used, which is the radial basis function kernel.
=> Apps: Rename kernel to rbf_kernel

strawberryfields/__init__.py
We normally suggest users can import the applications layer through commands like:
```python
from strawberryfields.apps import clique
```
However, users may end up on occasion using:
```python
import strawberryfields as sf
sf.apps.clique.grow(...)
```
This PR allows for this.
=> Apps: add module to SF __init__

requirements.txt
This PR adds Plotly to the developer `requirements.txt` (but not to `setup.py`!). Plotly is used for applications in Strawberry Fields.
=> Add plotly to requirements

setup.py
**Description of the Change:** Removes the outdated dependency on the `hafnian` library. This library was renamed to `thewalrus`, so the project effectively depends on two versions of the same library.
**Benefits:** n/a
=> Remove outdated hafnian dependency

setup.py
Bumps `thewalrus` dependency to version 0.9 to fix an import error in the apps module.
=> Require thewalrus>=0.9 to fix an import error in the apps module.

README.rst
**Context:**
The image URL in the readme appears to be pointing to a deleted branch.
Modify the image URL to point to master.
**Benefits:**
The image is displayed on the readme :slightly_smiling_face:
=> Fix image URL on readme

requirements.txt
The `requirements.txt` file also had a minimum version of `thewalrus` that is not sufficient. I have also updated the other requirements to at least match those in `setup.py`
=> Bring requirements.txt in to line with setup.py

.github/CHANGELOG.md, MANIFEST.in
The data added in the applications layer must be added to `MANIFEST.in` for it to be included in the sdist.
=> Add apps data to manifest

.github/CHANGELOG.md, requirements.txt, setup.py, strawberryfields/__init__.py, strawberryfields/ops.py, strawberryfields/parameters.py, tests/integration/test_decompositions_integration.py
**Context:**
In sympy 1.4, the `atan2` function has a bug in its implementation.  In PR #163 `sf.ops.CXgate` is implemented using a decomposition that needs `atan2`, so a workaround was used. The workaround could not handle the case `s=0`, however. The bug has been fixed in sympy 1.5.
* Adds `sympy >= 1.5` as an installation requirement (this was missing before)
* Removes the workaround code
* Modifies the tests so they test the `s=0` case as well.
**Benefits:**
The code is simplified, and can also handle the `s=0` case.
=> sympy.functions.atan2 has been fixed in sympy 1.5, workaround removed.

.github/CHANGELOG.md, doc/code/sf_program.rst, doc/index.rst, doc/introduction/circuits.rst, examples/optimization.py, strawberryfields/__init__.py, strawberryfields/ops.py, strawberryfields/parameters.py, strawberryfields/program.py, tests/frontend/test_io.py, tests/frontend/test_parameters.py, tests/integration/test_parameters_integration.py, tests/integration/test_tf_symbolic.py, tests/integration/test_utils_integration.py
**Context:**
The symbolic parameter system should be able to handle TensorFlow objects being passed through it,  without actually depending on TF. This can be done using the `tensorflow` printer in SymPy. SymPy requires TF 2.0 to work.
* Symbolic parameter syntax and use is described in the docs.
* TF objects can now appear as `Operation` parameters only by binding free parameters to them when the `Program` is run.
* TF-related symbolic parameter tests and examples are fixed and temporarily disabled, until SF has been migrated to TF 2.0.
* Symbolic parameters are now consistently evaluated right before the backend API call, not before.
**Benefits:**
Once the TF 2.0 migration is done, SF can again be used in symbolic TF computations.
**Related GitHub …
=> Symbolic parameter / TF compatibility, documentation

doc/code/sf.rst, doc/code/sf_backends.rst, doc/code/sf_engine.rst, doc/code/sf_io.rst, doc/code/sf_parameters.rst, doc/code/sf_program.rst, doc/introduction/circuits.rst, strawberryfields/__init__.py, strawberryfields/engine.py, strawberryfields/io.py, strawberryfields/parameters.py, strawberryfields/program.py
**Context:**
SF uses `automodapi` to document the code. For each module, automodapi creates one html page for the module, containing summary tables listing the classes and functions in the module namespace, and separate html pages for each class/function, with links between them. This has the side effect of sometimes creating duplicate pages: for example, if in module `A` we have `from B import X` , automodapi will generate two practically identical html pages for the class `X`, namely `A.X.html`  and `B.X.html`. Ideally we'd like to have only `B.X.html`.
Multiple html pages for the same object lead to warnings when building the docs, as Sphinx does not know to which page wildcard links of the form `.X` are supposed to point.
There are (at least) three ways to prevent automodapi from …
=> Remove duplicate automodapi pages for imported objects.

.github/CHANGELOG.md, strawberryfields/backends/fockbackend/circuit.py, strawberryfields/backends/fockbackend/ops.py, tests/backend/test_beamsplitter_operation.py, tests/backend/test_twomode_squeezing_operation.py
**Context:**
The beamsplitter  and two-mode squeezing operation have special symmetries, namely SU(2) and SU(1,1). This implies that their matrix elements B_{nm}^{kl}, T_{ij}^{kl} satisfy the selection rules
This implies that one can contract pure states (without loss of generality we assume only two modes) using one less loop as follows
and 
where c_{ij} is the tensor representing the two mode state and n is the cutoff in Fock space.
Similarly for a mixed state one should be able to do the update of the state using two less summations.
These observations should result in significant savings when acting beamsplitters and two-mode squeezing in the Fock backend.
Added a new apply_twomode_gate function to the fockbackend that can be used instead of …
=> Custom contraction for beamsplitter, two-mode squeezing and diagonal operators

doc/introduction/intro_photonics/conventions/gates.rst
The description of the S2gate given in the docs is incosistent with the one in the backends.
This PR correct the docs so that they are consistent with the backends. I have checked the decomposition given in terms of BSgate and Sgates and it is correct.
The way to confirm that indeed we implement S2gate(r,phi) = \exp( r e^(i \phi) a^\dagger b^\dagger  - \hc) is to note that
S2gate(r,phi) |0,0> = |0,0> + r e^{i \phi} |1,1>  for  r<<1.
If instead one used what was written in the docs one would get  |0,0> - r e^{i \phi} |1,1>.
=> Docs S2gate consistent with backends

.github/CHANGELOG.md, strawberryfields/apps/clique.py, strawberryfields/apps/subgraph.py, tests/apps/test_subgraph.py
This PR adds support for node-weights in the search algorithms of the `subgraph` module.
=> Apps: Update subgraph functions to accept node weights

requirements.txt, setup.py
**Context:**
This attempts to solve #304.
Adds the `numba` requirement as >=0.48.
**Benefits:**
SF can be imported.
N/A
#304
=> Adding numba to requirements

default_config.toml, doc/introduction/configuration.rst, doc/introduction/starship.rst, strawberryfields/configuration.py, tests/frontend/test_configuration.py
**Context:**
Currently `"localhost"` is set as a default hostname in Strawberry Fields. This requires the user to change it each time they want to connect to the Xanadu cloud platform.
Making `"platform.strawberryfields.ai"` as the default hostname, such that users can simply just run `sf.store_account(AUTH_TOKEN)` when connecting the Xanadu cloud platform.
**Benefits:**
Less configuration is needed.
N/A
N/A
=> Change default hostname

strawberryfields/decompositions.py
**Context:**
Currently, the rectangular decomposition is such that the identity matrix is implemented as a series of swaps. While this still gives the correct unitary, it is harder to implement on the hardware.
With this modification, the identity is decomposed such that there are no unnecessary swaps.
**Benefits:**
Easier to implement on hardware.
N/A
=> Rectangular decomposition: Identity fix

strawberryfields/io.py
Updating the `io.load` function docstring.
=> Updating the `io.load` function docstring.

tests/frontend/test_circuitspecs_gaussianunitary.py
The test `tests/frontend/test_circuitspecs_gaussianunitary.py::test_non_primitive_gates` was accidentally marked `xfail` on a commit during the `demo` branch development. This PR reverts that change.
**Benefits:** additional test will run
=> Remove accidental xfail commit from the demo branch

.github/CHANGELOG.md, strawberryfields/api/connection.py, strawberryfields/engine.py
**Context:**
The `run()` and `run_async()` methods on `RemoteEngine` accept an optional shots parameter which defaults to 1. This parameter always overrides the value specified in the Blackbird script or resulting `Program` object, but there should be a way to use the Blackbird/`Program` shots value if the overriding value is not explicitly specified. In particular, the `sf` CLI has no way of specifying the number of shots via its command-line arguments, so programs cannot be run with more than 1 shot.
The `RemoteEngine.run()`, `RemoteEngine.run_async()`, and `Connection.create_job()` interfaces are modified to make the `shots` parameter default to `None`. When the job is created, the shots value in the `Program` object will be overridden only if the `shots` …
=> Make shots parameter optional for RemoteEngine and Connection

strawberryfields/api/connection.py, tests/api/test_connection.py
**Context:**
Remote engine job cancellation.
Fixed a bug that prevented jobs from being cancelled when cancelling a running job.
**Benefits:**
Jobs can be cancelled now.
None.
None.
=> Fix a json-issue in the cancel_job method of sf.api.connection.Connection

doc/algorithms/gaussian_boson_sampling.rst, doc/gallery/gate_synthesis/GateSynthesis.ipynb, doc/gallery/minimizing_correlations/minimizing_correlations.ipynb, doc/gallery/state_learner/StateLearning.ipynb, doc/tutorials/tutorial_machine_learning.rst, doc/tutorials/tutorial_teleportation.rst, examples/GaussianBosonSampling.ipynb, examples/gaussian_cloning.py, examples/optimization.py, examples/quantum_neural_network.py, strawberryfields/api/connection.py, strawberryfields/apps/sample.py, strawberryfields/circuitspecs/X12.py, strawberryfields/circuitspecs/X8.py, strawberryfields/circuitspecs/__init__.py, strawberryfields/engine.py, strawberryfields/io.py, strawberryfields/program.py, tests/api/conftest.py, tests/api/test_connection.py, tests/api/test_remote_engine.py, tests/frontend/test_engine.py, tests/frontend/test_io.py, tests/integration/test_algorithms.py, tests/integration/test_engine_integration.py, tests/integration/test_measurement_integration.py, tests/integration/test_ops_integration.py, tests/integration/test_tf_symbolic.py
**Context:**
Currently in Strawberry Fields:
* The user must initialize an engine or a compile a program with a specific chip target, e.g., `X8_01`, `X12_01`, etc. However, there should be a way for the user to initialize an engine or compile a program for a chip _family_ (e.g., `eng.run("X8")`, `prog.compile("X8")`), with the Remote engine delegating the job to a specified default for each family.
* `LocalEngine.run()` and `RemoteEngine.run()` have inconsistent signatures:
```python3
LocalEngine.run(self, program, *, args=None, compile_options=None, run_options=None)
RemoteEngine.run(self, program: Program, shots: Optional[int] = None)
```
While these appear as two separate issues, they are quite interconnected. Since `eng.run()` internally calls the `prog.compile()` method, both engines …
=> Unify RemoteEngine.run() and LocalEngine.run() signatures, and allow for default chip specs for each device family.

strawberryfields/engine.py
**Description of the Change:** In #337 the signature of the `RemoteEngine` was updated. In particular, it should accept a `shots` keyword argument. However, there was a bug where `kwargs` was updated, but then *reassigned* to the result of `kwargs.update` (which is `None`). This resulted in the shots not being added to the blackbird scripts which are sent for remote execution. Jobs were summarily rejected.
**Benefits:** This PR fixes the above bug
**Possible Drawbacks:** We need to add a test which would have detected this bug before merging.
**Related GitHub Issues:** PR #337
=> Fixing kwarg assignment bug in engine.py

doc/introduction/photonic_hardware.rst, doc/tutorials/tutorial_X8.rst, strawberryfields/__init__.py
**Context:**
The `cli` module contains a `ping` function to verify the connection to the Xanadu cloud platform. When used in a Python script (and as an option with the command-line interface), an `AttributeError` is raised.
Imports `cli.ping` in `__init__.py` and adjusts the examples to use `sf.ping()` for brevity.
**Benefits:**
The `ping` function can be used from within a Python script after importing `strawberryfields`:
```python
import strawberryfields as sf
sf.ping()
```
Shortening the call to `sf.ping()` in the examples is less descriptive when compared to `sf.cli.ping()`.
#338
=> Import cli.ping in __init__.py

strawberryfields/api/connection.py
**Context:**
The error message produced by an unsuccessful request made by the `Connection` class is somewhat opaque and lacks context for effectively diagnosing and/or debugging the problem.
Extends the error message produced by failed `Connection` API requests with the contents of the `meta` field (if present) in the error response body.
**Example:**
Before:
```
File ".../strawberryfields/api/connection.py", line 170, in create_job
"Failed to create job: {}".format(self._format_error_message(response))
strawberryfields.api.connection.RequestFailedError: Failed to create job:  (validation-error): The server cannot process the request because it is invalid. Please check the request parameters and try again.
```
After:
```
File …
```
=> Add more details to Connection error message

strawberryfields/api/connection.py, strawberryfields/engine.py, tests/api/test_remote_engine.py
**Context:**
The `RemoteEngine.run_async()` method had the erroneous line
```python
kwargs = kwargs.update(self._backend_options)
```
The `dict.update` method is an in-place method, and returns `None`, resulting in an incorrectly compiled blackbird program.
* The line above has been modified to remove the assignment.
* A tests has been added to catch this behaviour in future.
* The logic in determining the run options has been moved to `RemoteEngine.run_async`, as it makes more logical sense here than as part of the `Connection` object.
* I noticed that SF was not providing a default value for the number of shots in the remote engine. Local engine has `shots=1` by default, but this is because the `fock` and `tf` backends don't support multishot sampling yet, …
=> Fix RemoteEngine.run_async kwargs bug, and add test

Makefile
Make clean-docs remove build files in doc/code/api. If this isn't done, there can be warnings when building docs due to old function/class stubs made by `automodapi`.
=> Make clean-docs remove build files in doc/code/api

.github/CHANGELOG.md, doc/requirements.txt, strawberryfields/_version.py
**Context:** Prepares for the 0.13.0 release candidate 0 release.
* Bumps version number to 0.13.0rc0
* Updates changelog with recent PRs, and corrects Python example
* Pins `sphinx-gallery` to version 0.5, as 0.6 was recently released, breaking the documentation CSS.
**Benefits:** n/a
=> Bump version number to 0.13.0rc0

strawberryfields/decompositions.py, tests/frontend/test_decompositions.py
**Context:**
Make `takagi` better by being clever when the input matrices are real.
Adds an extra `if` branch in the case where the matrices are real.
**Benefits:**
Uses extra information and is faster than the current `takagi` which does not use the extra information of when the input matrix is real.
None?
closes https://github.com/XanaduAI/strawberryfields/issues/349
=> Takagi for real

.github/CHANGELOG.md, strawberryfields/backends/fockbackend/circuit.py
**Context:**
To calculate homodyne measurements in the Fock backend, a Hermite polynomial probability distribution is computed. However, due to floating point precision error, values in the probability distribution may have a small negative value (e.g., `-2e-20`), causing issues when `np.random.multinomial` is subsequently called.
Small negative values are set to zero in the probability distribution using NumPy fancy indexing.
**Benefits:** Fixes #354 
**Related GitHub Issues:** #354
=> Fixes bug where negative probabilities can be calculated during Homodyne measurement in the Fock backend

.github/CHANGELOG.md, doc/code/sf_cli.rst, doc/code/sf_configuration.rst, strawberryfields/__init__.py, strawberryfields/_version.py, strawberryfields/api/connection.py
* Bump version number to v0.13.0 for release
* Fix documentation build errors, by skipping functions that are being imported in multiple places
* Fix small backdoor for older versions of NumPy, by enforcing `allow_pickle=False` when loading sampled data.
**Benefits:** n/a
=> Bump version number for 0.13.0 release

strawberryfields/backends/base.py
Details on diff: `..note` -> `.. note` and removing `:code:` for rendering.
=> Correcting note box for measure_fock

.github/CHANGELOG.md, strawberryfields/api/connection.py, strawberryfields/api/result.py, tests/api/test_result.py
**Context:** The `Results.__str__()` method attempted to print out the contained state and samples, even if the backend didn't return a state.
**Description of the Change:** Removes the printing of contained data from the class string representation.
```python
>>> results
<Result: num_modes=3, shots=1, contains state=True>
>>> results.state
<FockState: num_modes=3, cutoff=5, pure=True, hbar=2>
>>>  results.samples
array([[0, None, -0.1783017830178295]], dtype=object)
```
**Benefits:** No longer errors if the backend does not return a state object. Provides metadata about the results object, rather than the underlying state and sample data, which is a better separation of logic.
**Possible Drawbacks:** We should add more metadata to the results object, including:
- The program used to …
=> Fix printing of results object when it contains no state

.github/CHANGELOG.md, strawberryfields/api/connection.py, strawberryfields/api/job.py, strawberryfields/engine.py, tests/api/test_connection.py, tests/api/test_remote_engine.py
**Context:**
Currently, a failed remote job produces a generic error message that is difficult to diagnose. The job info response from the remote platform contains a `meta` field that is currently unused, but has some information that may be useful, e.g.,
```python
{
'error_code': 'hardware-message-error',
'error_detail': 'The job failed because the message received from the hardware could not be understood.'
}
```
- Add a `meta` property to the `Job` class. In the event of job failure, this dictionary will contain an `error-code` and `error-detail`.
- Refresh the `meta` attribute (along with `status`) when `Job.refresh()` is called.
- Add the contents of `meta` to the error message for a failed job.
Example:
- Previous error message: `"The remote job …
=> Add error details for failed remote job

.github/CHANGELOG.md, README.rst, doc/_static/install.html, doc/development/development_guide.rst, setup.py
**Context:**
Support for Python 3.5 is deprecated and thus shouldn't be stated anywhere in Strawberry Fields.
Traces of Python 3.5 is removed from `setup.py`, `README.rst`, the documentation `install.html`, and the development guide.
**Benefits:**
No mentions of Python 3.5 will be left in Strawberry Fields: the readme will display the correct version along with the development guide, and all installation files will be set to ignore this version of Python.
N/A
N/A
=> Remove traces of Python 3.5

strawberryfields/apps/__init__.py, strawberryfields/apps/train/__init__.py, strawberryfields/apps/train/embed.py, tests/apps/test_embed.py
This PR adds a submodule for embedding trainable parameters for GBS distributions. It is part of a new `train` module in the apps layer dedicated to training and optimizing GBS distributions. 
The core functionality is the ability to express GBS parameters (weights) as a function of trainable parameters. This includes calculating derivatives of weights with respect to the parameters, which will be required for gradient-based optimization
=> Add embedding submodule for training GBS distributions

.github/CHANGELOG.md, strawberryfields/backends/states.py, tests/backend/test_states.py
**Context:**
https://github.com/XanaduAI/strawberryfields/issues/386
Adds the parity expectation value function to StrawberryFields for Gaussian backend states (previously only implemented for states in the Fock backend).
**Benefits:**
Parity expectations will now work for any state in any backend.
None
https://github.com/XanaduAI/strawberryfields/issues/386
=> Adds the Parity Operator for States in the Gaussian Backend (WIP)

.github/CHANGELOG.md, strawberryfields/apps/qchem/dynamics.py, tests/apps/qchem/test_dynamics.py
This PR adds the function `prob` to `sf.apps.qchem.dynamics` to compute the probability of observing a desired excitation in a list of samples.
=> Add a function to qchem for computing state probability

doc/requirements.txt, strawberryfields/backends/__init__.py
**Context:**
With #378, the import for the `TFBackend` was changed. This unfortunately caused TF to be a requirement for StraberryFields.
As a further item, for the requirements of the docs, a wheel is specified for TheWalrus. As instead, the latest release candidate could help out to choose the correct wheel,
* Reverts changes to the TF import
* Uses the release candidate of TheWalrus for the docs
**Benefits:**
TF doesn't have to be a requirement for SF
N/A
N/A
=> Reverting TFBackend import & TheWalrus rc in docs requirements

doc/requirements.txt, tests/apps/test_similarity.py
A [new version](https://pypi.org/project/sphinx-autodoc-typehints/#history) of sphinx-autodoc-typehints was released yesterday that [drops support](https://github.com/agronholm/sphinx-autodoc-typehints/commit/9a966fe012c7d10baeacd7a55c32cb378d5f5320) for `sphinx < 3.0`. However, we currently version pin `sphinx` to `2.2.2`.
This new release hence caused the documentation to stop building, and a quick fix is to version pin `sphinx-autodoc-typehints` to `1.10.3` as is done in this PR.
Current RTD builds are breaking:
=> Fix docs building

.github/CHANGELOG.md, strawberryfields/api/devicespec.py, strawberryfields/engine.py, tests/api/test_remote_engine.py
**Context:** The current default compiler for devices that don't specify a preferred compiler is `Xcov`. This compiler is the most general, but can lead to permutations of the unitary.
**Description of the Change:** Changes the default compiler to `Xunitary`. This compiler only compiles the unitary, not the initial squeezers, however avoids any unintentional permutations.
**Benefits:** Avoids permutations of the qumodes
**Possible Drawbacks:** Slightly more strict; initial `S2gate` operations must match the chip layout.
=> Changes the default compiler to be Xunitary

.github/CHANGELOG.md, strawberryfields/_version.py, strawberryfields/engine.py, tests/api/test_remote_engine.py
**Summary:**
* Adjusts the signature of the `RemoteEngine.run` method to be able to accept the `recompile` argument added in #447 to the `RemoteEngine.run_async` method.
* Increments the version number to `0.15.1`
=> Increment version number to v0.15.1

.github/CHALLENGES.md
The link to `contribution guidelines` is incorrect in CHALLENGES.md, and has been updated.
Fixes #453.
=> Update link in the challenges file.

.github/workflows/format.yml
This PR changes the github format file so that checks are made against python 3.8. This fixes issues that were arising in other PRs, e.g., in #463
=> Update github format.yml for python 3.8

.travis.yml, Makefile, tests/apps/train/test_param.py, tests/frontend/test_sf_cli.py
**Context:**
Some tests in `test_tdmprogram.py` seems to be failing stochastically. They seem to pass locally when running a single test file, but fail in the PR, causing some confusion.
[pytest-randomly](https://pypi.org/project/pytest-randomly/) is added to the SF tests and automatically set to a seed of 42, which is the same that was used earlier in many cases. The makefile and travis are updated to use this.
**Benefits:**
Tests can now be run deterministically.
Optimally, we would remove the `randomly-seed=42` from the tests, causing the seed to be set randomly each time, helping us discover potential bugs due to the stochastic nature of some tests. By resetting the seed before each test, we may miss failures that might be …
=> Add pytest-randomly

tests/frontend/test_tdmprogram.py
Makes all the tests in `test_tdmprogram` aware of the value of `sf.hbar` without any monkey business.
=> No gorilla patching

requirements.txt, setup.py
**Context:**
`antlr4-python3-runtime` is pinned at 4.8 in Blackbird, while it's still pinned at 4.7.2 in Strawberry Fields. This causes version conflicts during install. This is likely found now due to the new pip version released today which uses the new dependency resolver by default (and thus discovered this issue and tried to fix it by downloading many different versions of packages and comparing them). 
Since antlr isn't required directly by SF (and was only added [here](https://github.com/XanaduAI/strawberryfields/pull/312/files#r391028692) due to failing tests), it can be removed, and is then installed with Blackbird instead.
`antlr4-python3-runtime` is removed from `requirements.txt`
**Benefits:**
No version conflicts between SF and Blackbird due to …
=> Remove antlr4 requirement + pin Blackbird>=0.3.0 in setup.py

.github/CHANGELOG.md, requirements.txt, strawberryfields/api/result.py, strawberryfields/engine.py, tests/api/test_result.py
**Context:**
Currently the representation of the `Result` object doesn't work for TDM programs due to the samples having dimension 3 (shots, spatial modes, timebins) instead of 2.
Quick fix that assumes that it's a TDM program if the samples dim is 3, and thus prints the correct representation.
**Benefits:**
Just writing `eng.run(tdm_prog)` or `res = eng.run(tdm_prog); print(res)` works, and actually prints something useful.
Might not be the nicest solution, but since `Result` doesn't know what type of program the samples are from, I think this works well for now. Might need to be revisited later with some further changes to the `Result` class (incorporating e.g. where the results are from).
None
=> Fix result representation for TDM programs

.github/CHANGELOG.md, strawberryfields/tdm/tdmprogram.py, tests/frontend/test_tdmprogram.py
**Context:**
`eng.run(prog)` crashes when attempting to use a single parameter list in the `TDMProgram` context.
A fix is added that changes a single free parameter to a list when only passing a single parameter list to the `TDMProgram` context.
**Benefits:**
The following now works:
```python
prog = sf.TDMProgram(2)
eng = sf.Engine("gaussian")
with prog.context([1, 2]) as (p, q):
ops.Sgate(p[0]) | q[0]
ops.MeasureHomodyne(p[0]) | q[0]
eng.run(prog)
```
None
None
=> Fix issue with single parameter list

.github/CHANGELOG.md, strawberryfields/engine.py, tests/frontend/test_engine.py, tests/frontend/test_tdmprogram.py
**Context:**
Setting the number of shots in `TDMProgram.run_options` doesn't change the number of shots used when calling `eng.run()`, without passing a shots value.
Shots now checked and retrieved in the following order: shots passed via `eng.run(prog, shots=shots)` > `prog.run_options` > default value, which is 1. The left-most available being the one that is used.
**Benefits:**
If `TDMProgram.run_options` is set, that value is used rather than falling back on the default value. This can be the case, for example, when converting from a Blackbird script. Without this fix the shots values set in the Blackbird script would simply be ignored when running the engine.
None
None
=> Fix run_options not being used

.github/CHANGELOG.md, strawberryfields/io.py, tests/frontend/test_io.py
**Context:**
The convert-to-python-code functionality in SF interactive should be moved to SF.
Added a `generate_code` function to `io.py` that generates SF code from a `Program` or a `TDMProgram`, returning the code as a string. If an engine is passed, the engine-related code is also serialized.
**Benefits:**
It's possible to convert a program/engine into code directly via SF.
None
None
=> Add program code generator function

.github/CHANGELOG.md, strawberryfields/api/connection.py
**Context:**
The Xanadu platform API will soon be implementing versioning, allowing clients to 
request a  particular version of the API using the 'Accept-Version' HTTP header. This header will eventually be mandatory.
Adds an `api_version` str property to `Connection` with the value `1.0.0`. On init, adds
'Accept-Version' header to `Connection._headers` with the value of `api_version`.
**Benefits:**
Future releases of sf will be able to use the platform API once versioning becomes
mandatory. Platform will be able to support older versions of sf following breaking
API changes.
None, beyond the established drawbacks of versioning the platform API - older
releases of sf will eventually be incompatible with the platform once versioning …
=> Adds api_version property, adds 'Accept-Version' to headers

.github/CHANGELOG.md, strawberryfields/ops.py, tests/frontend/test_ops_gate.py
This PR fixes a bug in Dgate, Coherent, and DisplacedSqueezed where TensorFlow tensors raise an error if fed with an extra dimension due to batching.
=> Fix bug in Dgate, Coherent, and DisplacedSqueezed

.github/CHANGELOG.md, strawberryfields/api/connection.py, tests/api/test_connection.py
**Context:**
The platform backend is moving to a new OAuth based authentication flow using offline refresh tokens and access tokens. 
* Adds an authentication call to retrieve a short-lived access token using the long lived refresh token stored in the configuration (offline token)
* Wraps all API calls to retrieve a new access token if the current one has expired (resulting in a 401 response)
**Benefits:**
More secure and easier user credential management.
Not backwards compatible, all users will be required to generate new tokens and update strawberry fields when the new authentication mechanism is activated.
N/A
=> Implement OAuth refresh token flow

.github/CHANGELOG.md, strawberryfields/__init__.py, strawberryfields/_version.py
Increments the version to v0.17.0.
Also, updates the changelog (adds some new entries) as well as the docstring for the `sf.about()` method.
=> Increment version number to v0.17.0

strawberryfields/backends/bosonicbackend/backend.py
=> dummy change

.github/CHANGELOG.md, strawberryfields/api/connection.py, tests/api/test_connection.py
**Context:**
The current version of StrawberryFields sends an incorrect version header to the Xanadu Quantum Cloud API.
- Update the `Accept-Version` header of requests sent from the `strawberryfields.api.connection` module to `0.2.0` instead of `1.0.0`
- Add a custom User-Agent string which sends a header in the standard format `StrawberryFields/0.17.0` where `0.17.0` is the current version of StrawberryFields
**Benefits:**
- Allows compability with the XQC platform in future iterations where API versioning will be more strict
- The `User-Agent` string gives important contextual information to the XQC API which can be used to provide custom behaviour in the future (for example, rewriting behaviour in the case of problematic requests, or providing …
=> Rewrite XQC API version to 0.2.0 and add User-Agent

strawberryfields/backends/base.py, strawberryfields/backends/bosonicbackend/backend.py, strawberryfields/compilers/__init__.py, strawberryfields/compilers/bosonic.py, strawberryfields/ops.py, tests/backend/test_bosonic_backend.py, tests/backend/test_mbsqueeze_operation.py
**Context:** The bosonic backend simulates states as linear combinations of Gaussians in phase space
- Adds preparation backend and frontend methods for GKP, cat and Fock states to the bosonic backend
- Adds the run_prog and init_circuit methods to bosonic/backend.py which are the engines for running sf Programs in the bosonic backend
- Adds the bosonic compiler
- Adds tests for these new backend methods
**Benefits:**
- Simulation of bosonic qubits
=> Bosonic backend nongaussian

strawberryfields/tdm/tdmprogram.py
**Context:**
The `reshape_samples` function in `tdmprogram.py` currently works by popping elements from the `all_samples` dictionary that's being sent in as an argument, and then inserting them into a new dictionary which is then returned. This causes the sent in `all_samples` dictionary to be empty after having reshaped the samples (which might be confusing for the user, since this is nowhere stated).
This is not really an optimal way of handling things, and should probably be fixed. 
The popping of samples from the input `all_samples` dictionary is changed to indexing, while keeping track of used indices. Thanks to @lneuhaus for [pointing this out](https://github.com/XanaduAI/strawberryfields/pull/542#discussion_r580376229)!
**Benefits:**
This method …
=> Replace `pop` with indexing in `reshape_samples`

.github/CHANGELOG.md, .github/CONTRIBUTING.md, README.rst, TESTS.rst, doc/development/development_guide.rst
**Context:**
Cleanup documentation for ease of contribution based on this [slack conversation](https://xanadu-quantum.slack.com/archives/CA2U56VDE/p1616180499012000).
**Benefits:**
Makes it easier for new contributors.
N/A
N/A
=> Docs cleanup for contribution

.github/CHANGELOG.md, .github/PULL_REQUEST_TEMPLATE.md, Makefile, dev_requirements.txt, doc/development/development_guide.rst
**Context:**
Discussed on #561 
Adds a development environment section to development docs, and an associated `dev_requirements.txt` for installation. Includes a `black` format script run by `make format` with associated instructions in development docs and PR template.
**Benefits:**
Makes contribution easier.
N/A
N/A
=> Development requirements and formatting

.github/CHANGELOG.md, strawberryfields/backends/tfbackend/__init__.py, strawberryfields/backends/tfbackend/backend.py, strawberryfields/backends/tfbackend/circuit.py, strawberryfields/backends/tfbackend/ops.py, strawberryfields/backends/tfbackend/states.py, tests/frontend/test_engine.py
**Context:**
Resolves #486 
Make tensorflow dtype adjustable by user by adding a `dtype` optional argument to `backend_options`. Follows existing patterns for optional arguments.
**Benefits:**
User can adjust `dtype`, i.e.:
```
prog = sf.Program(2)
eng  = sf.Engine("tf", backend_options={"cutoff_dim": 50, "dtype": tf.complex128})
with prog.context as q:
Sgate(0.8)         | q[0]
Sgate(0.8)         | q[1]
BSgate(0.5,0.5)  | (q[0], q[1])
BSgate(0.5,0.5)  | (q[0], q[1])
state    = eng.run(prog).state
N0,N0var = state.mean_photon(0)
N1,N1var = state.mean_photon(1)
print(N0)
print(N1)
print('analytical:',np.sinh(0.8)**2)
```
N/A?
#486
=> Tf engine dtype

doc/requirements.txt
[Docutils version 0.17](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-17-2021-04-03), released on April 3rd, contains a new HTML5 writer that uses HTML5 semantic tags (`<main>`, `<section>`, `<header>`, `<footer>`, `<aside>`, `<figure>`, and `<figcaption>`) rather than `<div>`. This breaks the CSS on the website.
This PR pins docutils to version 0.16.
=> Pin docutils to version v0.16

.github/CHANGELOG.md, strawberryfields/tdm/tdmprogram.py, tests/frontend/test_tdmprogram.py
**Context:**
Device specifications for TDM programs that are exposed by Xanadu's device API used to include a field `modes` with data like
```
{
"concurrent": 2,
"spatial": 1,
"max": {"temporal": 100},
}
```
This format was recently changed into (ex generis):
```
{
"concurrent": 2,
"spatial": 1,
"temporal_max": 100
}
```
This PR brings Strawberry Fields up to date with the new format.
**Benefits:**
TDM programs can run on Xanadu hardware.
None.
None.
=> Fix TDM "modes" validation to match XQC API

.github/CHANGELOG.md, doc/introduction/photonic_hardware.rst, strawberryfields/backends/gaussianbackend/gaussiancircuit.py, tests/frontend/test_program.py
**Context:**
The Xanadu Quantum Cloud simulator, formerly called `simulon`, now has the target name `simulon_gaussian`. This change was made to support many different simulon types in the future.
- References to `simulon` in documentation and tests have been changed to `simulon_gaussian`.
- A formatting change is made in `strawberryfields/backends/gaussianbackend/gaussiancircuit.py`. It appears that the black version on CI has been upgraded since the last commit, which now checks new elements in docstrings. This change has been made here instead of in a separate PR.
**Benefits:**
People reading the docs will not try to submit jobs to a simulator that doesn't exist :slightly_smiling_face: 
n/a
n/a
=> Change simulon target to simulon_gaussian

.github/CHANGELOG.md, strawberryfields/parameters.py
**Context:**
Some optimization tasks using Strawberry Fields were showing increased memory allocation, although no state was being left (i.e., the engine was reset, state objects recreated, etc.).
Parameters in Strawberry Fields might be numeric or symbolic. To represent both, SymPy is used. When using gate parameters that are internally created, Strawberry Fields evaluates the parameter to get the numeric value using SymPy.
Evaluating the parameters depends on the `sympy.lambdify` function, which [internally caches data using `linecache`](https://github.com/sympy/sympy/blob/aa96b23bb98f00542101c08d8ea02ef83949310b/sympy/utilities/lambdify.py#L876). The memory increase was found to be due to this caching.
Changes the `par_evaluate` function which does the …
=> Reduce the use of SymPy lambdify

doc/requirements.txt, requirements.txt, setup.py
**Context**
The new release of TensorFlow version 2.5 pins `numpy ~= 1.19.2`. As Strawberry Fields pins `numpy>=1.20`, installing SF in a clean environment results in version conflicts between TensorFlow's and SF's `numpy` version requirement.
**Changes**
Pins `numpy>=1.19.2` in `requirements.txt`, `doc/requirements.txt` and `setup.py`.
**Related issues**
Closes #580.
=> numpy>=1.19.2 as requirement

setup.py
As per the discussion in #581.
=> Ease back `numpy>=1.17.4` in `setup.py`

examples/quantum_neural_network.py
**Context**
When increasing the number of modes in the `examples/quantum_neural_network.py` file containing the QNN tutorial (e.g., having `modes=2), the gradient contains `nan` values and the optimization will continue using tensors filled with `nan` values.
**Changes**
For computing the fidelity of the difference between the measured ket and the target state, a safe absolute value function is being used. This function allows ensuring that the gradient for getting the absolute value at the `0.0` point will return `0.0`.
**Related issues**
Closes #588
=> Fixes the QNN example to use a safe absolute value function for multiple modes

.github/CHANGELOG.md, doc/requirements.txt, requirements.txt, strawberryfields/io.py, strawberryfields/parameters.py, tests/frontend/test_io.py
**Context:**
There are a few issues when attempting to convert an SF circuit with feed-forwarding to Blackbird. If any parameter is found to be symbolic, it's cast as a string rather than keeping it as a `blackbird.RegRefTransform` as it would be if loaded directly from a script to Blackbird. For example, the following SF circuit
```python
with prog.context as q:
Coherent(math.sqrt(5/4), math.atan(1/2)) | q[0]
Sgate(2, 0) | q[2]
Sgate(-2, 0) | q[1]
BSgate(0.7854, 0) | (q[1], q[2])
BSgate(0.7854, 0) | (q[0], q[1])
MeasureP | q[1]
MeasureX | q[0]
Xgate(q[0].par*1.41421356237000) | q[2]
Zgate(q[1].par*1.41421356237000) | q[2]
```
will, when transformed into a Blackbird program, converting `q[0].par*1.41421356237000` and `q[1].par*1.41421356237000` into the strings `"1.41421356237000*q0"` and …
=> Keep symbolic expressions for Blackbird programs

requirements.txt, strawberryfields/backends/gaussianbackend/backend.py, strawberryfields/backends/gaussianbackend/gaussiancircuit.py, strawberryfields/compilers/__init__.py, strawberryfields/compilers/gaussian.py, strawberryfields/compilers/passive.py, strawberryfields/ops.py, tests/frontend/compilers/test_passive.py, tests/frontend/test_ops_channel.py, tests/integration/test_ops_integration.py
**Context:**
If you want to run a circuit on a large number of modes, with a large depth of passive optical operations, this can be quite slow. In this PR, we introduce a new compiler which works for fully passive circuits. This is able to compile any passive, linear operation into a single matrix. This can then be applied as a single operation.
The "passive" compiler can compile passive linear circuits. The PassiveChannel operation can apply arbitrary passive multimode operations to a state.
**Benefits:**
Should allow for faster computation of e.g. large multimode covariance matrices which are formed by a large depth of operations.
Only implemented for the Gaussian backened.
Not compatible with active operations, such as squeezing, …
=> new passive circuit compiler

.github/CHANGELOG.md, strawberryfields/tdm/tdmprogram.py, tests/frontend/test_tdmprogram.py
**Context:**
We recently changed the allowed gate parameters for `TD2`. The `Rgate` phase can now be both positive and negative. With this change, requested programs did not pass the validation step in the program validation any more when negative phases were set. The reason was that when the code was supposed to validate the phases of the `BSgate` (where only positive values are allowed), it used the values set for the `Rgate` phases, which were occasionally negative. 
The proposed solution now uses the correct values in the above described validation step for each parameter.
**Benefits:**
Fixed a bug. Code behavior should be closer to what one expects now.
I did not fully understand the logic. In particular, it seems to me that the …
=> Fix validation in TdmProgram.compile

strawberryfields/backends/gaussianbackend/gaussiancircuit.py, tests/backend/test_heterodyne.py
**Context:** Generaldyne sampling in the gaussian backend
**Description of the Change:** Fixes the formula used for sampling generaldyne outcomes in the gaussian backend.
The covariance matrix of the sampling distribution needed also to depend on the covariance of the state onto which the target state was begin measured.
Updated the test in test_heterodyne to account for this.
**Benefits:** Correct heterodyne sampling (homodyne unaffected).
**Possible Drawbacks:** None.
=> Generaldyne sampling in gaussian

.github/CHANGELOG.md, strawberryfields/io.py, tests/frontend/test_io.py
**Context:**
Measurement arguments are _always_ compiled into Blackbird keyword arguments when using `io.to_blackbird`, while all other gate arguments are being stored as non-keyword arguments. This causes some issues when attempting to match templates with parameter values ([specifically for QKD](https://github.com/XanaduAI/xanadu-og-config/pull/143#event-5215091659)).
Switch measurement arguments from being compiled into keyword arguments in Blackbird to non-keyword arguments, to conform with the rest of the gate arguments.
**Benefits:**
Matching parameter values with measurement arguments works the same as when matching with gate arguments.
If someone somewhere uses the fact that measurement arguments always are stored as keyword …
=> Switch measurements kwargs to args in `io.to_blackbird`

strawberryfields/tdm/tdmprogram.py, tests/frontend/test_tdmprogram.py
**Context:**
The TDM compiler is failing when attempting to compile TDM program using device specs with symbolic template parameters in operations. This is due to the compiler seeing anything that is not a string (e.g., a value _or_ a symbolic parameter) as a hard-coded parameter, which a template parameter is not, and concludes that the values in the spec differ from the values in the program.
* Template parameters are no longer seen as a hard-coded parameter type.
* If a template parameter is used instead of a p-type parameter, it can still be used to validate the parameter values in the device spec if it's named the same there.
**Example:** The following works, with all `{s}` values being validated using the gate parameter range `'s': [[0.0, 99999999.]]`. …
=> Symbolic parameter support in TDM compiler

.github/CHANGELOG.md, doc/development/migration_guides.rst, doc/introduction/circuits.rst, strawberryfields/api/result.py, strawberryfields/backends/bosonicbackend/backend.py, strawberryfields/engine.py, strawberryfields/tdm/tdmprogram.py, tests/api/test_remote_engine.py, tests/api/test_result.py, tests/backend/test_bosonic_backend.py, tests/frontend/test_engine.py, tests/frontend/test_parameters.py, tests/frontend/test_tdmprogram.py
**Context:**
As part of the XCC integration, the Result class needs to be updated.
* The `Result` class now only takes a result dictionary containing all samples.
* The `samples` property returns the first entry in the result dictionary (which should be the pure samples).
* `all_samples` have been renamed to `samples_dict`.
* `Result._is_stateful` has been removed in favour of `self._state is not None`.
**Benefits:**
Things work better together with XCC and the dictionary type samples that will be returned from the HW.
* The `samples` property returns the first entry in the result dictionary _assuming_ they are the pure samples).
* `Result._is_stateful` has been removed, and does not seem to have a clear use case.
**Related GitHub …
=> Update Result class to work with XCC

.github/CHANGELOG.md, strawberryfields/__init__.py
**Context:**
These changes should've been included in the #652 PR. 
* Adds `DeviceSpec` and `Result` to `strawberryfields.__init__.__all__`.
* Updates a code snippet in the changelog regarding how to use `DeviceSpec` and `Result`.
**Benefits:**
Things are slightly nicer.
None
None
=> Add missed API extraction updates

.github/workflows/docs.yml, doc/requirements.txt, requirements-ci.txt, strawberryfields/backends/tfbackend/ops.py
**Context:** [PR #295](https://github.com/XanaduAI/thewalrus/pull/295) on The Walrus deprecates the C++ implementation of  `gaussian_gate` and `grad_gaussian_gate` in favor of the numba implementation. This in turn modifies the signatures of the imported functions.
**Description of the Change:** This PR will use the new implementation of `gaussian_gate` and `grad_gaussian_gate` on The Walrus
**Benefits:** The Walrus has less C++ dependencies
**Possible Drawbacks:** None
**Related GitHub Issues:** None
=> Use refactored gaussian gate from The Walrus

strawberryfields/engine.py
**Context:**
Some traces of removed methods were left from the `DeviceSpec` XCC integration update.
Removes non-existing `DeviceSpec.fill_template` and `DeviceSpec.is_formatted` calls in `RemoteEngine.run_async`
**Benefits:**
It will now work to run TDM programs remotely using the updated `DeviceSpec` class.
None
None
=> Remove `fill_template` calls in `RemoteEngine.run_async`

.github/CHANGELOG.md, strawberryfields/program.py, strawberryfields/tdm/tdmprogram.py
**Context:**
The `Program.compile` method sets the program target (which is `None` at start) to the device target (e.g., `X8_01`) and updates `Program.compile_info`. This never happens in `TDMProgram.compile`, so `prog.target` is always `None`, which in turn causes the Blackbird serialize method to ignore the passed shots option, since it has no target name.
For example, the BlackbirdProgram.target for a regular `sf.Program` could be `{'name': 'X8_01', 'options': {'shots': 1}}` which would serialize into target `X8_01 (shots=1)`. The corresponding for an `sf.TDMProgram` would be `{'name': None, 'options': {'shots': 1}}`, which wouldn’t serialize since there’s no target name.
`program.compile_info` and `program.target` are set if compilation (i.e., …
=> Compile info and target to `TDMProgram.compile`

.github/CHANGELOG.md, strawberryfields/program.py, tests/frontend/test_program.py
**Context:**
The platform returns a flat dictionary entry for the maximum number of measurements allowed when running jobs on Simulon. Strawberry Fields currently expects a nested dictionary entry (which was added in #545).
`Program.assert_max_number_of_measurements` is updated to use the flat modes entry when checking for maximum allowed measurements. 
**Benefits:**
`simulon_gaussian` is one step closer to working again.
None
None
=> Update max measurements check

.github/CHANGELOG.md, doc/introduction/circuits.rst, doc/requirements.txt, strawberryfields/backends/bosonicbackend/backend.py, strawberryfields/engine.py, strawberryfields/ops.py, strawberryfields/result.py, tests/api/test_result.py, tests/backend/test_bosonic_backend.py, tests/integration/test_engine_integration.py
**Context:**
There's no way to access non-samples results (i.e., metadata) in the `Result` class.
* A `Result.raw` method is added that returns the raw result dictionary.
* A `Result.metadata` method is added that returns the metadata of the results (i.e., everything except the `"output"` entry).
* Tests are added for the `Result` class.
* A setter method is added for `Result.state` allowing a state to be set iff a state has not previously been set and the `Result` object contains `samples_dict` samples, indicating that it's a local simulation.
**Benefits:**
* Results metadata can be accessed without using the private `Result._result` method.
* The `Result` class is properly tested.
* The state can be properly set in the result object.
**Possible …
=> Raw results and metadata

.github/CHANGELOG.md, examples/teleportation.py
**Context:**
The teleportation example fails to teleport the state. Setting the BS phase to 0 apparently fixes this for various numeric examples. The phase was 0 in the previous version of this example as well as the theory part of the html example in the docs.
The beam splitter phase in the teleportation example was set to 0.
**Benefits:**
The teleported state on q[2] can now be confirmed to have its probability distribution around the original state (via Wigner plots etc.).
None
=> fix teleportation.py beamsplitter phase (to 0)

.github/CHANGELOG.md, strawberryfields/engine.py, strawberryfields/ops.py, tests/frontend/test_engine.py, tests/frontend/test_tdmprogram.py
**Context:**
Simulating a circuit requires to execute the measurements to return results. This execution can take long time, however there are cases where no execution is required, e. g., when calculating the covariance matrix of the circuit.
If `shots=None` the backend bypasses the execution (i.e. the `apply` method) of any op of class `Measurement` that belongs to the circuit.
**Benefits:**
Users can define circuits and bypass measurements to avoid lengthy executions of simulations if not needed.
=> `shots=None` will not execute any measurement

.github/workflows/tests.yaml
**Context:**
Quick fix for an issue with SymPy caching expressions and wrongly using a cached register reference instead of the new one. See issue #683 for details.
Sets the `SYMPY_USE_CACHE` environment variable to "no" in CI, so that no caching is done when running tests. 
**Benefits:**
Certain cases when SymPy parameters are cached and incorrectly retrieved will (hopefully) no longer happen in the CI tests.
This is just a quick fix for the CI tests. The issue is still present in the code-base.
#683
=> Set `SYMPY_USE_CACHE` environment variable to "no"

.github/workflows/tests.yaml, tests/backend/test_states_probabilities.py, tests/integration/test_ops_integration.py
**Context:**
Currently, no tests are being run without TensorFlow installed. This makes it easy to mistakenly add code that is dependent on TensorFlow to core Strawberry Fields, which doesn't have TensorFlow as a requirement.
Adds a CI action that runs the relevant tests in an environment without TensorFlow installed. 
This is done by 
- adding a new strategy to the `core-test` job where pytest will run all tests except those marked with `"tf"`. That is, setting `OPTIONS="not tf"`,
- creating a new environment variable `TF_DEPENDENCIES="tensorflow|tensorboard"` listing the dependencies to be removed from the `requirements-ci.txt` file,
- using `awk` to remove dependencies listed on `TF_DEPENDENCIES` from the `requirements-ci.txt` file when `OPTIONS="not …
=> Run CI tests without Tensorflow

.github/CHANGELOG.md, strawberryfields/device.py, strawberryfields/program.py, tests/api/test_devicespec.py
**Context:**
Currently, there's no check against using different targets in the specification (`Device.target`, or `Device._spec["target"]`) and in the Blackbird layout (target field in `Device.layout`, or `BlackbirdProgram.target`). This shouldn't be an issue for the user unless the specification is incorrect, although it's safer to have a check for this at device creation directly.
* A `Device.assert_spec` static method is added which checks that the target in the layout is the same as the target field in the specification. This check is also performed at `Device` initialization.
* If no target is specified in the layout, the device target is used instead. This is useful e.g., when compiling a program with a device (currently, if this would be attempted …
=> Assert spec and layout target equality

.github/CHANGELOG.md, strawberryfields/program.py, tests/frontend/test_program.py, tests/frontend/test_tdmprogram.py
**Context:**
The compiler create a linked copy of the program by calling `Program._linked_copy()`, which retains the same regrefs. Since the copy is shallow, it also keeps the same TDM parameters in a TDM program. These parameters are updated by the compiler and thus changed in both the compiled program _and_ the initial program, while the circuit is only changed in the compiled program.
* `Program._linked_copy()` is updated to create a deep-copy of all attributes except the ones containing register references, including e.g., the TDM parameters.
* The initial program's regrefs are linked to the compiled programs regrefs instead of implicitly referenced by using a shallow copy.
**Benefits:**
The compiler actually returns a copy of the program without …
=> Deep copy from `Program.compile()`

strawberryfields/engine.py
**Context:**
`X12_01` is no longer in use. Instead, `X12` should point to `X12_02`.
`X12` now points to `X12_02`.
**Benefits:**
The correct `X12` device is targeted.
None
None
=> Change default `X12` target to `X12_02`

requirements.txt, setup.py
**Context:**
A new version of XCC has been released, containing changes improving the download speeds samples from running remote jobs.
The version of XCC is bumped to the latest version in `requirements.txt` and `setup.py`.
**Benefits:**
Remote jobs now benefit from the faster sample downloading in the latest version of XCC.
None
None
=> Bump XCC version

.github/CHANGELOG.md, strawberryfields/tdm/tdmprogram.py, tests/frontend/test_space_unroll.py, tests/frontend/test_tdmprogram.py
**Context:**
When a program is compiled it is locked, and no further changes can be made to it. This means that a compiled program cannot be unrolled unless `Program.locked = False`.
`TDMProgram.unroll` and `TDMProgram.space_unroll` unlock the program before unrolling and, if it was locked before, locks it again.
**Benefits:**
Users no longer have to manually unlock programs before attempting to unroll them.
None
None
=> (un)locking when (un)rolling

doc/requirements.txt
New version of `protobuf` is released causing the documentation to fail.
```
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/google/protobuf/descriptor.py:560: in __new__
_message.Message._CheckCalledFromGeneratedFile()
E   TypeError: Descriptors cannot not be created directly.
E   If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
E   If you cannot immediately regenerate your protos, some other possible workarounds are:
E    1. Downgrade the protobuf package to 3.20.x or lower.
E    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
The temporary hotfix is to pin `protobuf<4.21.0`. However, this should be considered temporary, and …
=> Pin `protobuf<4.21.0`

.github/CHANGELOG.md, strawberryfields/program.py, strawberryfields/tdm/tdmprogram.py, tests/frontend/test_program.py
**Context:**
There are two methods that check that a various number of mode parameters are within the allowed limit specified in the device specification. These can easily, and should, be combined into a single method.
`Program.assert_number_of_modes` and `program.assert_max_number_of_measurements` are combined into a single `assert_modes` method.
**Benefits:**
The logic is simplified.
None
None
=> Combine assert modes

.github/CHANGELOG.md, strawberryfields/tdm/tdmprogram.py
**Context:**
If a rolled circuit is compiled and then later unrolled and then re-rolled, the un-compiled circuit, which has previously been stored, is used instead of rolling the circuit back to the compiled version.
Store correct rolled circuit before unrolling (fixes issue when rolled circuit has changed due to e.g., compilation).
**Benefits:**
Circuits can now be: compiled -> unrolled -> rolled without being reverted to the pre-compiled version.
None
None
=> Unrolling fix

.github/CHANGELOG.md, requirements.txt, strawberryfields/engine.py, tests/api/test_remote_engine.py
**Context:**
To avoid overflow issues job results are automatically converted to `np.int64` objects. It can be of interest to keep the results as `np.int8` objects.
A flag `integer_overflow_protection` has been added to `RemoteEngine.run()` allowing users to return job results as `np.int8`.
**Benefits:**
* Job results can now be retrieved without converting integers to `np.int64` objects by setting `integer_overflow_protection=False` (default `True`) when running a program via `RemoteEngine.run()`.
None
None
=> Integer overflow protection flag

strawberryfields/engine.py, tests/api/test_remote_engine.py
**Context:**
If a compiler is used that it _not_ an X-series compiler (e.g., not Xcov or Xunitary), validation using Xstrict should not be used.
Validation using Xstrict is only performed when a program has been compiled using an X-series compiler.
**Benefits:**
Potential issues when running compiled programs are solved.
None
None
=> Limit `Xstrict` validation to X-series compilers

setup.py
**Context:**
Strawberry Fields requires Blackbird >= 0.4.0, but it's currently at >=0.3.0.
Increment Blackbird requirement to 0.4.0.
**Benefits:**
Less chance of something failing to an old version of Blackbird.
None
None
=> Increment Blackbird requirement

.github/workflows/upload.yml, strawberryfields/backends/tfbackend/circuit.py, strawberryfields/backends/tfbackend/ops.py, strawberryfields/backends/tfbackend/states.py, strawberryfields/decompositions.py, tests/apps/train/test_cost.py, tests/integration/test_tf_integration.py
**Context:**
Automatic PyPI release action is failing due to failing tests when simply running tests with `pytest tests` (instead of `make tests`).
* Adds a random seed to the tests run on the upload action.
* Sets the env var `SYMPY_USE_CACHE` to `"no"` to avoid issue with sympy caching (see #684 for details).
* Fixes tolerances in a few tests that were failing too often (specifically when running without setting a seed).
* Replaces `_einsum_v1` with `tf.einsum` in all places but one (still an issue with `sf.backends.tfbackend.ops.conditional_state()` which I wasn't able to solve) and also removed the einsum test marked XFAIL (was XPASSing).
**Benefits:**
* It should now be possible to run all tests directly using `pytest tests`.
* The automatic PyPI …
=> Fix release action
